### ISSUE TITLE
Teachable machine generated Model

### ISSUE THREAD

**Issue by mmmoakley** [google-coral/edgetpu#200]
I used the teachable machine web site to train a bunch of Images.
I created 3 different classes
I exported Tendorflow Lite and EdgeTPU format
copied the files over to board and executed
edgetpu_detect_server --model model_edgetpu.tflite --labels labels.txt

Returned this error
Traceback (most recent call last):
  File "/usr/bin/edgetpu_detect_server", line 11, in <module>
    load_entry_point('edgetpuvision==1.0', 'console_scripts', 'edgetpu_detect_server')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect_server.py", line 33, in main
    run_server(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 43, in run_server
    camera = make_camera(args.source, next(gen), args.loop)
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect.py", line 144, in render_gen
    engines, titles = utils.make_engines(args.model, DetectionEngine)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 53, in make_engines
    engine = engine_class(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 85, in __init__
    'This model has {}.'.format(output_tensors_sizes.size)))
ValueError: Dectection model should have 4 output tensors!This model has 1.

**Comment by Namburger** [comment]
@mmmoakley It is not a bug, the teachable machine produces a classification model which only produces 1 output tensor, you are trying to load it in a detection engine, which expects 4 output tensors. See here: https://github.com/google-coral/edgetpu/blob/master/src/cpp/detection/engine.cc#L16

You should run this model on the `edgetpu_classify_server` instead

**Comment by mmmoakley** [comment]
works, thanks again
