### ISSUE TITLE
USB "Not enough bandwidth" after many runs of python inference

### ISSUE THREAD

**Issue by ppershing** [google-coral/edgetpu#207]
I came across this several times by now.

I am trying to train many different architectures and see their accuracy on edge TPU. For this, I run a simple interence python program multiple times and once in a while I get
```
Traceback (most recent call last):
  File "/home/ppershing/miniconda3/envs/tf/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/home/ppershing/miniconda3/envs/tf/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 120, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./benchmark.py", line 59, in <module>
    main()
  File "./benchmark.py", line 36, in main
    interpreter = make_interpreter(args.model)
  File "./benchmark.py", line 23, in make_interpreter
    EDGETPU_SHARED_LIB, {"device": device[0]} if device else {}
  File "/home/ppershing/miniconda3/envs/tf/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 164, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1
```

with dmesg showing
```
[1242023.964228] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1242023.984440] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1242689.790359] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1242689.810459] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1287628.532042] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1287628.556215] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1287654.272292] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1287654.292544] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1287940.607902] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1287940.632007] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1287964.823831] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1287964.844020] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1288246.583297] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1288246.603426] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1288287.543248] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1288287.563351] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1288564.278784] usb 4-2: reset SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[1288564.302717] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1288564.302955] xhci_hcd 0000:00:14.0: Not enough bandwidth
[1288564.303042] usb 4-2: Busted HC?  Not enough HCD resources for old configuration.
[1288564.310315] usb 4-2: USB disconnect, device number 14
[1288564.506335] usb 4-2: new SuperSpeed Gen 1 USB device number 15 using xhci_hcd
[1288564.526753] usb 4-2: LPM exit latency is zeroed, disabling LPM.
[1288564.527080] usb 4-2: New USB device found, idVendor=18d1, idProduct=9302, bcdDevice= 1.00
[1288564.527084] usb 4-2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[1288564.527436] xhci_hcd 0000:00:14.0: Not enough bandwidth
[1288564.527547] usb 4-2: can't set config #1, error -12
```

Note that this error cannot be unstuck by simply re-trying or even unplugging the device. I need to reset whole USB hub.

**Comment by Namburger** [comment]
May i ask if you are plugging the Accelerator in a usb2 or usb3 port?

**Comment by ppershing** [comment]
> May i ask if you are plugging the Accelerator in a usb2 or usb3 port?

Should be USB3. This is relevant part of `lsusb -t`
```
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 2: Dev 3, If 0, Class=Application Specific Interface, Driver=, 5000M
```

**Comment by Namburger** [comment]
I see, would you be able to reproduce this under a usb2 port?

**Comment by ppershing** [comment]
I tried to reproduce this on usb2 but I failed so far. Note though that I don't have a clear reproduction on usb3 (that is - it happens from time to time but I am not exactly sure how to trigger this reliably. I tried cycling my quick benchmark tool many times in a loop but the reproduction is flaky)

Do you have an idea of what to focus on more? So far I cannot say whether the error is related to
a) many times startup of the process/loading of the delegate
b) many times running inference/set_tensor in one session

**Comment by Namburger** [comment]
@ppershing we've seen similar issue but only with usb3 and very specific architecture, this is usually caused after a long period of time. Could you possibly submit the model so I can reproduce?

**Comment by ppershing** [comment]
@Namburger Unfortunately, this would be very tricky. I am basically running an architecture search so it is very hard to attribute if the problem is in single of my architectures, a subset of them or if all of them are leaking resources in some way. In order to speed up the process -- should I be testing process restarts / model reloads or just running one model over prolonged periods of time is enough?

**Comment by Namburger** [comment]
@ppershing one model over a long period of usually may cause it, however any of the models that we have in our stress test never causes this issue (we do have continuous stress test for all of our canned model). 
We did have one model submission from a user that we were able to use to reproduce it. It only happens over usb3 port and it takes a very long time, this is currently being looked into

**Comment by ppershing** [comment]
@Namburger finally reliably reproduced with this single model https://www.dropbox.com/s/4gzaxn8k3nrm4oh/poolx3r5_cos_adam_750_001.tflite?dl=0 (my previous reproductions we spread over dozens of models so it was hard to say which one/ if all are responsible)

**Comment by usbguru** [comment]
Hi @ppershing 
The USB Accelerator is a development tool.  On occasion I have had to unplug it and plug it back in to continue.  We do continuous, rigorous testing on the production products such as the SoM.

As Nam suggested, a USB2 evaluation could be useful.  Could you use it at USB2 speeds if "Not Enough Bandwidth" error goes away?

Since this occurs rarely, and you want to automate the testing, you could try completely turning off the USB Accelerator with a programmable USB hub, as discussed here:  https://github.com/google-coral/edgetpu/issues/252
