### ISSUE TITLE
Couldn't use MobileNet SSD v2 (Faces) for object detection

### ISSUE THREAD

**Issue by krittin-kulrat** [google-coral/edgetpu#258]
I tried to run detect_image.py example using [MobileNet SSD v2 (Faces) model](https://coral.ai/models/)
[https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py](https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py)

> ----INFERENCE TIME----
> Note: The first inference is slow because it includes loading the model into Edge TPU memory.
> Traceback (most recent call last):
>   File "detect_image.py", line 106, in <module>
>     main()
>   File "detect_image.py", line 85, in main
>     objs = detect.get_objects(interpreter, args.threshold, scale)
>   File "/home/pi/.local/lib/python3.7/site-packages/pycoral/adapters/detect.py", line 190, in get_objects
>     class_ids = common.output_tensor(interpreter, 1)[0]
>   File "/home/pi/.local/lib/python3.7/site-packages/pycoral/adapters/common.py", line 29, in output_tensor
>     return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
> IndexError: list index out of range

I know that this model is different from other model since it doesn't require label file but I wish to know how to use this model properly
Thank you

**Comment by krittin-kulrat** [comment]
Look like the model is corrupt during downloading process.
