### ISSUE TITLE
ValueError: Failed to load delegate from edgetpu.dll

### ISSUE THREAD

**Issue by vvkuryshev** [google-coral/edgetpu#281]
I had problem on Windows 10 and downgraded runtime version to edgetpu_runtime_20200728.zip and tflite_runtime to 2.1.0 (as it was described [here](https://github.com/google-coral/edgetpu/issues/260#issue-747388549)). This allowed the drivers to be installed afterwards, but trying to run the test script again failed. What could be the problem here?

```
C:\coral\tflite\python\examples\classification>python classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 162, in load_delegate
delegate = Delegate(library, options)
File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 121, in init
raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "classify_image.py", line 122, in
main()
File "classify_image.py", line 99, in main
interpreter = make_interpreter(args.model)
File "classify_image.py", line 73, in make_interpreter
{'device': device[0]} if device else {})
File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 165, in load_delegate
library, str(e)))
ValueError: Failed to load delegate from edgetpu.dll

**Comment by vvkuryshev** [comment]
The problem was because the old version was not removed before the edgetpu_runtime version was changed. After reinstalling edgetpu_runtime_20200728 everything works. Three times slower than [here](https://coral.ai/docs/accelerator/get-started), but it worked. Perhaps the difference in speed due to my not newest hardware.

```C:\coral\tflite\python\examples\classification>python classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
97.0ms
9.1ms
8.9ms
8.8ms
9.1ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.77734
