### ISSUE TITLE
mdt shell can not work on MacOS Catalina

### ISSUE THREAD

**Issue by kingliantop** [google-coral/edgetpu#282]
Following the instructions, the mdt can find the device, but mdt shell can not ssh to the Coral Dev board:

MacOS 10.15.7
(base) stevenlian-macbookpro:~ stevenlian$ mdt devices
indigo-mole		(192.168.1.15)
(base) stevenlian-macbookpro:~ stevenlian$ mdt version
MDT version 1.5.2

(base) stevenlian-macbookpro:~ stevenlian$ mdt shell
Waiting for a device...
Connecting to indigo-mole at 192.168.1.15
Traceback (most recent call last):
  File "/Users/stevenlian/cloud/anaconda3/bin/mdt", line 8, in <module>
    sys.exit(main())
  File "/Users/stevenlian/cloud/anaconda3/lib/python3.7/site-packages/mdt/main.py", line 162, in main
    exit(command.run(sys.argv[1:]))
  File "/Users/stevenlian/cloud/anaconda3/lib/python3.7/site-packages/mdt/command.py", line 76, in run
    return self.runWithClient(client, args)
  File "/Users/stevenlian/cloud/anaconda3/lib/python3.7/site-packages/mdt/shell.py", line 74, in runWithClient
    channel = client.openShell()
  File "/Users/stevenlian/cloud/anaconda3/lib/python3.7/site-packages/mdt/sshclient.py", line 185, in openShell
    if self.shouldPushKey():
  File "/Users/stevenlian/cloud/anaconda3/lib/python3.7/site-packages/mdt/sshclient.py", line 74, in shouldPushKey
    compress=True)
  File "/Users/stevenlian/.local/lib/python3.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/Users/stevenlian/.local/lib/python3.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/Users/stevenlian/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/Users/stevenlian/.local/lib/python3.7/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/Users/stevenlian/.local/lib/python3.7/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
EOFError

**Comment by Namburger** [comment]
Hello, could you try ssh instead?
```
$ ssh -i ~/.config/mdt/keys/mdt.key mendel@192.168.1.15
```

**Comment by manoj7410** [comment]
@kingliantop Is this issue still reproducible ?
