### ISSUE TITLE
rpi style 40-pin gpio library support

### ISSUE THREAD

**Issue by saket424** [google-coral/edgetpu#300]
Does the coral have a library for interfacing with the 40-pin gpio on the Coral dev mini?

I am trying to interface an enviro+ sensor that works fine on a raspberry pi0 to instead work on a the google dev miniboard

https://github.com/pimoroni/enviroplus-python

python lcd.py
Traceback (most recent call last):
  File "lcd.py", line 3, in <module>
    import ST7735
  File "/home/mendel/enviro+stuff/enviroplus_exporter/venv3/lib/python3.7/site-packages/ST7735/__init__.py", line 26, in <module>
    import RPi.GPIO as GPIO
  File "/home/mendel/enviro+stuff/enviroplus_exporter/venv3/lib/python3.7/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!

I know the jetson folks have solutions https://github.com/NVIDIA-AI-IOT/jetbot/issues/18

**Comment by Namburger** [comment]
Hello, please check out the python-periphery library as documented here: https://coral.ai/docs/dev-board/gpio/#program-with-python-periphery
