### ISSUE TITLE
EdgeTPU produces wrong output if model contains duplicate weights

### ISSUE THREAD

**Issue by drasmuss** [google-coral/edgetpu#332]
Normally the output of a compiled/quantized model simulated in a standard TFLite interpreter matches the output from the same model simulated on a Coral board.  However, if the model contains duplicate weights (e.g. multiple layers that have weights with the same values) then the Coral board produces incorrect output.

Here is an example model demonstrating the issue
``` python
import numpy as np
import tensorflow as tf

do_bug = True

rng = np.random.RandomState(0)

inp = x = tf.keras.Input((32,))

kernel = rng.rand(32, 32)
for _ in range(5):
    x = tf.keras.layers.Dense(
        units=32,
        kernel_initializer=tf.initializers.constant(
            kernel + (0 if do_bug else rng.uniform(-1e-4, 1e-4, size=(32, 32)))
        ),
    )(x)

model = tf.keras.Model(inp, x)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8


def dataset_func():
    for _ in range(1000):
        yield [rng.uniform(-1, 1, size=(1, 32)).astype(np.float32)]


converter.representative_dataset = dataset_func

with open("model.tflite", "wb") as f:
    f.write(converter.convert())

interpreter = tf.lite.Interpreter(model_path="model.tflite")

interpreter.allocate_tensors()

x = rng.uniform(-1, 1, size=(1, 32))
input_tensor = interpreter.tensor(interpreter.get_input_details()[0]["index"])
output_tensor = interpreter.tensor(interpreter.get_output_details()[0]["index"])

input_tensor()[:] = x
interpreter.invoke()
y = output_tensor()

print(y)
```
Comparing the output from above versus running the `model.tflite` file through the `edgetpu_compiler` and executing it on the TPU will show that they produce different output.

Note that setting `do_bug=False` adds a small perturbation to all the weights so that they no longer match, and then the TFLite and TPU output match exactly.

**Comment by mbrooksx** [comment]
I don't see a different output. Here's an update that compiles it within the script and compares both:
```
import numpy as np
import os
import tensorflow as tf
from tflite_runtime.interpreter import load_delegate

do_bug = True

rng = np.random.RandomState(0)

inp = x = tf.keras.Input((32,))

kernel = rng.rand(32, 32)
for _ in range(5):
    x = tf.keras.layers.Dense(
        units=32,
        kernel_initializer=tf.initializers.constant(
            kernel + (0 if do_bug else rng.uniform(-1e-4, 1e-4, size=(32, 32)))
        ),
    )(x)

model = tf.keras.Model(inp, x)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8


def dataset_func():
    for _ in range(1000):
        yield [rng.uniform(-1, 1, size=(1, 32)).astype(np.float32)]


converter.representative_dataset = dataset_func

with open("model.tflite", "wb") as f:
    f.write(converter.convert())

os.system('edgetpu_compiler model.tflite')

def make_interpreter(model_file):
	model_file, *device = model_file.split('@')
	return tf.lite.Interpreter(
	model_path=model_file,
	experimental_delegates=[
	load_delegate('libedgetpu.so.1',{'device': device[0]} if device else {})])

results = dict()
x = rng.uniform(-1, 1, size=(1, 32))
for model in ['model.tflite', 'model_edgetpu.tflite']:
    interpreter = make_interpreter(model)
    interpreter.allocate_tensors()

    input_tensor = interpreter.tensor(interpreter.get_input_details()[0]["index"])
    output_tensor = interpreter.tensor(interpreter.get_output_details()[0]["index"])

    input_tensor()[:] = x
    interpreter.invoke()
    y = output_tensor()
    results[model] = y

    print(model + " : " + str(y))

# Compare Results
print('Difference between models:')
print(results['model.tflite'] - results['model_edgetpu.tflite'])
```

Output:
```
model.tflite : [[ 8  0  1 29  6 27 15  6  0 18 19  5 35  9  0  7  7 12  6  0  0 20 19 11
  17  0  0  0 16  1  0 28]]
model_edgetpu.tflite : [[ 8  0  1 29  6 27 15  6  0 18 19  5 35  9  0  7  7 12  6  0  0 20 19 11
  17  0  0  0 16  1  0 28]]
Difference between models:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
```

**Comment by drasmuss** [comment]
I don't think your example is actually running on the TPU, if I am understanding it correctly (it looks like you're just running the compiled model in the regular `tf.lite.Interpreter`). You should see the difference if you run on the actual device. Here is the script I am running on-device:
``` python
import numpy as np
import tflite_runtime.interpreter as tflite

interpreter = tflite.Interpreter(
    model_path="model_edgetpu.tflite",
    experimental_delegates=[tflite.load_delegate("libedgetpu.so.1", {})],
)

interpreter.allocate_tensors()

input_tensor = interpreter.tensor(interpreter.get_input_details()[0]["index"])
output_tensor = interpreter.tensor(interpreter.get_output_details()[0]["index"])

x = np.random.RandomState(0).uniform(-1, 1, size=(1, 32))

input_tensor()[:] = x
interpreter.invoke()
y = output_tensor()

print(y)
```

With the model generated with `do_bug=False` this gives the output 
```
[[ 8  0  1 29  6 27 15  6  0 18 19  5 35  9  0  7  7 12  6  0  0 20 19 11
  17  0  0  0 16  1  0 28]]
```
as expected.

With `do_bug=True` this gives the output
```
[[23 19 16 44 21 37 34 23 14 32 35 20 50 24 17 23 22 25 22 19  5 35 32 28
  28 21 12 12 32 18 16 42]]
```

**Comment by mbrooksx** [comment]
I'm running it on the TPU - I'm passing the delegate to the interpreter to handle the Edge TPU custom op. You can use tflite_interpreter.tflite.Interpreter or tf.lite.Interpreter - the important part is the delegate. I can verify it's a TPU model by removing the delegate and seeing it fail (or looking at the edgetpu model output in Netron)
```
Traceback (most recent call last):
  File "./duplicate_weights_bug.py", line 54, in <module>
    interpreter.allocate_tensors()
  File "/usr/local/google/home/michaelbrooks/.local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
```
If I do swap it to tflite_runtime.interpreter.Interpreter, the result is the same. What tflite_runtime do you have installed?

**Comment by drasmuss** [comment]
Something is definitely very different on your Coral board versus mine then. For one, as noted in the docs here https://coral.ai/docs/edgetpu/compiler/, the `edgetpu_compiler` doesn't usually run on the Coral board, as you appear to be doing in your script. 

> Note: The Edge TPU Compiler is no longer available for ARM64 systems (such as the Coral Dev Board), beginning with version 2.1. We recommend compiling your model on a more powerful desktop.

My board also doesn't have `tensorflow` installed, only the `tflite_runtime` (I tried for a while to install TensorFlow on the board, but couldn't get it to work). So `import tensorflow` doesn't work.

So something about our setup is very different, or I am misunderstanding how you are running things on the board.

My `tflite_runtime` version (on the board) is `2.1.0.post1`.

**Comment by Namburger** [comment]
@drasmuss This could be a bug that has been fixed! Suggest upgrading both `tflite_runtime` and `libedgetpu`, for reference:
```
mendel@bored-llama:~$ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0
mendel@bored-llama:~$ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
48c3bae94a8b324525b45f157d638dfd4e8c3be1
mendel@bored-llama:~$ dpkg -l | grep libedgetpu
ii  libedgetpu-dev                       15.0                                arm64        Development files for libedgetpu
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
```

**Comment by drasmuss** [comment]
I upgraded `tflite_runtime` and `libedgetpu`, but unfortunately I'm still getting the same incorrect output when running on the board.
```
mendel@coral:~/tmp$ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0
mendel@coral:~/tmp$ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
48c3bae94a8b324525b45f157d638dfd4e8c3be1
mendel@coral:~/tmp$ dpkg -l | grep libedgetpu
ii  libedgetpu-dev                       15.0                                arm64        Development files for libedgetpu
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
mendel@coral:~/tmp$ python3 tmp2.py
[[23 19 16 44 21 37 34 23 14 32 35 20 50 24 17 23 22 25 22 19  5 35 32 28
  28 21 12 12 32 18 16 42]]
```

**Comment by mbrooksx** [comment]
Yes, I was running on an x86 system with our USB Accelerator attached. It was unclear which Coral board you were referring to and the results are expected to be the same. I've switched to the Dev Board:

```
mendel@tuned-rabbit:~$ uname -a
Linux tuned-rabbit 4.14.98-imx #1 SMP PREEMPT Tue Nov 24 01:49:17 UTC 2020 aarch64 GNU/Linux
mendel@tuned-rabbit:~$ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0
mendel@tuned-rabbit:~$ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
48c3bae94a8b324525b45f157d638dfd4e8c3be1
mendel@tuned-rabbit:~$ dpkg -l | grep libedgetpu
rc  libedgetpu1-max:arm64                14.1                                arm64        Support library for Edge TPU
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
mendel@tuned-rabbit:~$ python3 ./run_weights.py 
model.tflite : [[ 8  0  1 29  6 27 15  6  0 18 19  5 35  9  0  7  7 12  6  0  0 20 19 11
  17  0  0  0 16  1  0 28]]
model_edgetpu.tflite : [[ 8  0  1 29  6 27 15  6  0 18 19  5 35  9  0  7  7 12  6  0  0 20 19 11
  17  0  0  0 16  1  0 28]]
Difference between models:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
```

Here's the code I ran:
```
import tflite_runtime.interpreter as tflite
import numpy as np

rng = np.random.RandomState(0)

def make_interpreter(model_file):
        model_file, *device = model_file.split('@')
        return tflite.Interpreter(
        model_path=model_file,
        experimental_delegates=[
        tflite.load_delegate('libedgetpu.so.1',{'device': device[0]} if device else {})])

results = dict()
x = rng.uniform(-1, 1, size=(1, 32))
for model in ['model.tflite', 'model_edgetpu.tflite']:
    interpreter = make_interpreter(model)
    interpreter.allocate_tensors()

    input_tensor = interpreter.tensor(interpreter.get_input_details()[0]["index"])
    output_tensor = interpreter.tensor(interpreter.get_output_details()[0]["index"])

    input_tensor()[:] = x
    interpreter.invoke()
    y = output_tensor()
    results[model] = y

    print(model + " : " + str(y))

# Compare Results
print('Difference between models:')
print(results['model.tflite'] - results['model_edgetpu.tflite'])
```

**Comment by drasmuss** [comment]
I was trying to think what the other differences could be between my setup and yours, and  noticed that I had an older version of the `edgetpu_compiler` (14.1). Upgraded that to 15.0, and now I have the expected output from the compiled model. Thanks for your help!
