### ISSUE TITLE
None of the Demo Edge TPU Models Work - "Module Provided has model identifier 'l><b', should be 'TFL3'"

### ISSUE THREAD

**Issue by Hana-Ali** [google-coral/edgetpu#430]
Using a Coral Devboard, and trying to run the `detect.py` file from https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py with the models on the https://coral.ai/models/object-detection/ page. Tried `ssd mobilenetv2` and `EfficientDet Lite,` both get the same error:

```
Traceback (most recent call last):
  File "detect.py", line 108, in <module>
    main()
  File "detect.py", line 73, in main
    interpreter = make_interpreter(args.model)
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 93, in make_interpreter
    model_path=model_path_or_content, experimental_delegates=delegates)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 351, in __init__
    experimental_preserve_all_tensors))
ValueError: Model provided has model identifier 'l><b', should be 'TFL3'
```

Not sure what the problem is, since both get the exact same error. Help is appreciated!

**Comment by manoj7410** [comment]
@Hana-Ali Can you share the exact command that you are executing ?

**Comment by Hana-Ali** [comment]
@manoj7410
It’s `python3 detect.py -m model.tflite -i image.jpg -l coco_labels.txt -o result.jpg`

**Comment by manoj7410** [comment]
@Hana-Ali What I want to know is the exact model name that you are trying to run.

**Comment by Hana-Ali** [comment]
@manoj7410
Ah, yes. I've tried EfficientDet-Lite3 and SSD MobileNet V2 from https://coral.ai/models/object-detection/

**Comment by manoj7410** [comment]
Can you make sure that you are using edgetpu compatible models ?

**Comment by Hana-Ali** [comment]
I downloaded them from the official coral page, so I think they should be compatible :/

**Comment by manoj7410** [comment]
At https://coral.ai/models/object-detection/ both edgetpu and CPU models are available. Please make sure that you download edgetpu models and not the CPU models. Can you please take a look again and confirm ?

**Comment by Hana-Ali** [comment]
Yes, I've downloaded the Edge TPU model (has that in the file name as well)

**Comment by hjonnala** [comment]
@Hana-Ali can you try with latest tflite_runtime and pycoral releases. https://github.com/google-coral/pycoral/releases

```
(newpycoral_venv) hemanthreddyj@hemanthreddyj-glaptop:~/coral/pycoral$ python3 examples/detect_image.py -m /home/hemanthreddyj/Downloads/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite -l /home/hemanthreddyj/Downloads/coco_labels.txt -i /home/hemanthreddyj/coral/pycoral/test_data/parrot.jpg -o /home/hemanthreddyj/Downloads/parrot_out.jpg 
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
23.54 ms
8.31 ms
7.97 ms
8.05 ms
8.03 ms
-------RESULTS--------
bird
  id:     15
  score:  0.7890625
  bbox:   BBox(xmin=66, ymin=105, xmax=466, ymax=892)
(newpycoral_venv) hemanthreddyj@hemanthreddyj-glaptop:~/coral/pycoral$ pip freeze
numpy==1.21.1
Pillow==8.3.1
pycoral==2.0.0
tflite-runtime==2.5.0.post1
(newpycoral_venv) hemanthreddyj@hemanthreddyj-glaptop:~/coral/pycoral$ 
```

**Comment by hjonnala** [comment]
Closing due to inactivity. Feel free to reopen if issue still exists.
