### ISSUE TITLE
Failed to load delegate from libedgetpu.so.1.0 on Arch

### ISSUE THREAD

**Issue by Flamingi** [google-coral/edgetpu#471]
### Description

I have compiled the Edge TPU runtime, Tensorflow lite and the PyCoral API from source on my Arch installation. After some initial troubles with the paths to my gcc libs, everyting went smoothly and I succesfully installed all necessary libs. When testing I get the mentioned error. I have used `gasket-dkms` from the AUR. The troubleshooting steps return the expected results. What could the issue be?

I also get the same error when installing the packages from AUR.

### Issue Type

Support

### Operating System

Linux

### Coral Device

Mini PCIe

### Programming Language

Python 3.9

### Relevant Log Output

```shell
[flamingi@archlinux ~]$ mkdir coral && cd coral
[flamingi@archlinux coral]$ git clone https://github.com/google-coral/tflite.git
[flamingi@archlinux coral]$ cd tflite/python/examples/classification
[flamingi@archlinux classification]$ bash install_requirements.sh
[...]
[flamingi@archlinux classification]$ python3 classify_image.py \
--model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels models/inat_bird_labels.txt \
--input images/parrot.jpg
Traceback (most recent call last):
  File "/home/flamingi/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/flamingi/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flamingi/coral/tflite/python/examples/classification/classify_image.py", line 122, in <module>
    main()
  File "/home/flamingi/coral/tflite/python/examples/classification/classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "/home/flamingi/coral/tflite/python/examples/classification/classify_image.py", line 72, in make_interpreter
    tflite.load_delegate(EDGETPU_SHARED_LIB,
  File "/home/flamingi/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
[flamingi@archlinux ~]$ python3 -c "from ctypes.util import find_library; print(find_library(\"edgetpu\"))"
libedgetpu.so.1
[flamingi@archlinux ~]$ lspci -nn | grep 089a
03:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
[flamingi@archlinux ~]$ ls /dev | grep apex
apex_0
[flamingi@archlinux ~]$ sudo dmesg | grep apex
[    4.284825] apex 0000:03:00.0: enabling device (0100 -> 0102)
[    9.493893] apex 0000:03:00.0: Apex performance not throttled due to temperature
[flamingi@archlinux ~]$ sudo dmesg | grep gasket
[    4.215675] gasket: loading out-of-tree module taints kernel.
[    4.230806] gasket: module verification failed: signature and/or required key missing - tainting kernel
[flamingi@archlinux ~]$ sudo dmesg | grep 089a
[    0.246820] pci 0000:03:00.0: [1ac1:089a] type 00 class 0x0000ff
[flamingi@archlinux ~]$ lspci -nnk
03:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Subsystem: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Kernel driver in use: apex
        Kernel modules: apex
```

**Comment by manoj7410** [comment]
@Flamingi Please share the output of below commands:

- uname -a
- modinfo gasket
- modinfo apex
- lspci -vvv

**Comment by Flamingi** [comment]
@manoj7410
BTW I failed to mention in the OP, I have tried it with the packages available on AUR as well and get the same error.
 Here is the output:
```
[flamingi@archlinux ~]$ uname -a
Linux archlinux 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64 GNU/Linux
[flamingi@archlinux ~]$ modinfo gasket
filename:       /lib/modules/5.14.3-arch1-1/updates/dkms/gasket.ko.zst
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.4
description:    Google Gasket driver framework
srcversion:     69BBD6B15F498A5A90971DD
depends:
retpoline:      Y
name:           gasket
vermagic:       5.14.3-arch1-1 SMP preempt mod_unload
parm:           dma_bit_mask:int
[flamingi@archlinux ~]$ modinfo apex
filename:       /lib/modules/5.14.3-arch1-1/updates/dkms/apex.ko.zst
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.2
description:    Google Apex driver
srcversion:     700E8BBBE9CC23C6EC17712
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       5.14.3-arch1-1 SMP preempt mod_unload
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
[flamingi@archlinux ~]$ sudo lspci -vvv
03:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU (prog-if ff)
        Subsystem: Global Unichip Corp. Coral Edge TPU
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 31
        IOMMU group: 7
        Region 0: Memory at e0400000 (64-bit, prefetchable) [size=16K]
        Region 2: Memory at e0300000 (64-bit, prefetchable) [size=1M]
        Capabilities: [80] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset- SlotPowerLimit 26.000W
                DevCtl: CorrErr- NonFatalErr- FatalErr- UnsupReq-
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+
                        MaxPayload 128 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr+ NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
                LnkCap: Port #1, Speed 5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
                        ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes, Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 5GT/s (ok), Width x1 (ok)
                        TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Range ABCD, TimeoutDis+ NROPrPrP- LTR+
                         10BitTagComp- 10BitTagReq- OBFF Not Supported, ExtFmt+ EETLPPrefix-
                         EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
                         FRS- TPHComp- ExtTPHComp-
                         AtomicOpsCap: 32bit- 64bit- 128bitCAS-
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
                         AtomicOpsCtl: ReqEn-
                LnkCap2: Supported Link Speeds: 2.5-5GT/s, Crosslink- Retimer- 2Retimers- DRS-
                LnkCtl2: Target Link Speed: 5GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete- EqualizationPhase1-
                         EqualizationPhase2- EqualizationPhase3- LinkEqualizationRequest-
                         Retimer- 2Retimers- CrosslinkRes: unsupported
        Capabilities: [d0] MSI-X: Enable+ Count=128 Masked-
                Vector table: BAR=2 offset=00046800
                PBA: BAR=2 offset=00046068
        Capabilities: [e0] MSI: Enable- Count=1/32 Maskable- 64bit+
                Address: 0000000000000000  Data: 0000
        Capabilities: [f8] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [100 v1] Vendor Specific Information: ID=1556 Rev=1 Len=008 <?>
        Capabilities: [108 v1] Latency Tolerance Reporting
                Max snoop latency: 0ns
                Max no snoop latency: 0ns
        Capabilities: [110 v1] L1 PM Substates
                L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
                          PortCommonModeRestoreTime=10us PortTPowerOnTime=10us
                L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
                           T_CommonMode=0us LTR1.2_Threshold=32768ns
                L1SubCtl2: T_PwrOn=20us
        Capabilities: [200 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES- TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr+ BadTLP+ BadDLLP+ Rollover- Timeout+ AdvNonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+
                AERCap: First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Kernel driver in use: apex
        Kernel modules: apex

```

**Comment by manoj7410** [comment]
@Flamingi Please share the output of below command as well:

- lscpu

Additionally, have you blacklisted the preinstalled 'apex' driver as mentioned at https://coral.ai/docs/m2/get-started/#2a-on-linux ?

**Comment by Flamingi** [comment]
@manoj7410 I have not blacklisted the apex driver as it was not preinstalled, `lsmod | grep apex` didn't print anything before installation

```
[flamingi@archlinux ~]$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 7 5700G with Radeon Graphics
    CPU family:          25
    Model:               80
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU max MHz:         3800.0000
    CPU min MHz:         1400.0000
    BogoMIPS:            7588.45
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 ss
                         e4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall f
                         sgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean
                         flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   256 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    4 MiB (8 instances)
  L3:                    16 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by manoj7410** [comment]
@Flamingi Please make sure that the secure boot is disabled on your machine. Also, I believe your user has access to the device.

I would suggest you to change the log_level of libedgetpu at https://github.com/google-coral/libedgetpu/blob/master/port/default/port_from_tf/logging.cc#L171 and then rebuild this library by following the instructions given at https://github.com/google-coral/libedgetpu#building.

You can set the log_level value from 1 to 10 (10 being the most detailed) to get the detailed output of libedgetpu and then we can understand where exactly it is failing.

**Comment by Flamingi** [comment]
Sorry for not updating this issue. I don't have the time and energy to deal with the shenanigans Arch throws into my way. I have abandoned the project and just installed Ubuntu Server, where the module works as expected.
