### ISSUE TITLE
Error in Demo at https://coral.ai/docs/dev-board/camera/#view-with-a-streaming-server

### ISSUE THREAD

**Issue by ba305** [google-coral/edgetpu#483]
### Description

Hello, I am running through this section of the camera setup: https://coral.ai/docs/dev-board/camera/#view-with-a-streaming-server. I am using a Coral Camera. In the demo, there are two models--the second one (face detection) works perfectly, but the first one (image classification) gives the following error:

```
edgetpu_classify_server \
> --model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite \
> --labels ${DEMO_FILES}/imagenet_labels.txt
Traceback (most recent call last):
  File "/usr/bin/edgetpu_classify_server", line 11, in <module>
    load_entry_point('edgetpuvision==7.0', 'console_scripts', 'edgetpu_classify_server')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/classify_server.py", line 28, in main
    run_server(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 43, in run_server
    camera = make_camera(args.source, next(gen), args.loop)
  File "/usr/lib/python3/dist-packages/edgetpuvision/classify.py", line 118, in render_gen
    labels = utils.load_labels(args.labels)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 28, in load_labels
    return {int(num): text.strip() for num, text in lines}
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 28, in <dictcomp>
    return {int(num): text.strip() for num, text in lines}
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 27, in <genexpr>
    lines = (LABEL_PATTERN.match(line).groups() for line in f.readlines())
AttributeError: 'NoneType' object has no attribute 'groups'
```

Does anybody else experience this? Since the face detection works, I feel like I am doing things mostly correctly (i.e., it seems like the rest of my setup is correct). Thank you!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mac OS

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, looks like line formatting issue. Can you try with this [imagenet_labels.txt](https://raw.githubusercontent.com/google-coral/test_data/cdc17e7b755ed29b93c67acc24df2a2317d03793/imagenet_labels.txt)

**Comment by ba305** [comment]
Hi Hemanth, yes, it works now! Thank you!
