### ISSUE TITLE
Error when run thr self converted coral model: RuntimeError: external/org_tensorflow/tensorflow/lite/kernels/elementwise.cc:59 input->type != expected_type (9 != 1)Node number 10 (RSQRT) failed to invoke.

### ISSUE THREAD

**Issue by JiashuGuo** [google-coral/edgetpu#504]
### Description

I have a coral pose estimation model that I converted from the trained chekpoint follow [https://github.com/scnuhealthy/Tensorflow_PersonLab](). The model is tested to be able to run as TFlite format, but when I run it on Coral edgetpu it reports the error:
 ```
Traceback (most recent call last):
  File "simple_pose.py", line 28, in <module>
    poses, inference_time = engine.DetectPosesInImage(np.uint8(pil_image))
  File "/home/dev/projects/coral/project-posenet/pose_engine.py", line 143, in DetectPosesInImage
    return self.ParseOutput(self.run_inference(img.flatten()))
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 136, in run_inference
    result = self._engine.RunInference(input)
```
Do you have any idea about what does this error means and is it able to be fixed? 

- Coral model: [https://drive.google.com/file/d/16U0f3MLYredanVlAjoEdBhOQvhlcLGOi/view?usp=sharing](kp_short_edgetpu.tflite)

- tf version 2.4.1

- Edge TPU Compiler version 16.0.384591198

run_model.py: 
```
import os
import numpy as np
from PIL import Image
from pose_engine import PoseEngine

os.system('wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/'
          'Hindu_marriage_ceremony_offering.jpg/'
          '640px-Hindu_marriage_ceremony_offering.jpg -O couple.jpg')

pil_image = Image.open('couple.jpg')
pil_image.resize((641, 481), Image.NEAREST)

engine = PoseEngine('/path/to/kp_short_edgetpu.tflite')
poses, inference_time = engine.DetectPosesInImage(np.uint8(pil_image))
print('Inference time: %.fms' % inference_time)

for pose in poses:
    if pose.score < 0.4: continue
    print('\nPose Score: ', pose.score)
    for label, keypoint in pose.keypoints.items():
        print(' %-20s x=%-4d y=%-4d score=%.1f' %
              (label, keypoint.yx[1], keypoint.yx[0], keypoint.score))
```
`pose_engine.py`:
```
import collections
import math

import numpy as np
from numpy.core.fromnumeric import put
from pkg_resources import parse_version
from edgetpu import __version__ as edgetpu_version
assert parse_version(edgetpu_version) >= parse_version('2.11.1'), \
        'This demo requires Edge TPU version >= 2.11.1'

from edgetpu.basic.basic_engine import BasicEngine
from edgetpu.utils import image_processing
from PIL import Image
import tensorflow as tf
from bilinear import bilinear_sampler
from scipy.ndimage.filters import gaussian_filter
from scipy.sparse import coo_matrix
from post_proc import *
KEYPOINTS = (
  'nose',
  'left eye',
  'right eye',
  'left ear',
  'right ear',
  'left shoulder',
  'right shoulder',
  'left elbow',
  'right elbow',
  'left wrist',
  'right wrist',
  'left hip',
  'right hip',
  'left knee',
  'right knee',
  'left ankle',
  'right ankle'
)

class Keypoint:
    __slots__ = ['k', 'yx', 'score']

    def __init__(self, k, yx, score=None):
        self.k = k
        self.yx = yx
        self.score = score

    def __repr__(self):
        return 'Keypoint(<{}>, {}, {})'.format(self.k, self.yx, self.score)


class Pose:
    __slots__ = ['keypoints', 'score']

    def __init__(self, keypoints, score=None):
        assert len(keypoints) == len(KEYPOINTS)
        self.keypoints = keypoints
        self.score = score

    def __repr__(self):
        return 'Pose({}, {})'.format(self.keypoints, self.score)

class PoseEngine(BasicEngine):
    """Engine used for pose tasks."""

    def __init__(self, model_path, mirror=False):
        """Creates a PoseEngine with given model.

        Args:
          model_path: String, path to TF-Lite Flatbuffer file.
          mirror: Flip keypoints horizontally

        Raises:
          ValueError: An error occurred when model output is invalid.
        """
        BasicEngine.__init__(self, model_path)
        self._mirror = mirror
        print(model_path)
        self._input_tensor_shape = self.get_input_tensor_shape()
        if (self._input_tensor_shape.size != 4 or
                self._input_tensor_shape[3] != 3 or
                self._input_tensor_shape[0] != 1):
            raise ValueError(
                ('Image model should have input shape [1, height, width, 3]!'
                 ' This model has {}.'.format(self._input_tensor_shape)))
        _, self.image_height, self.image_width, self.image_depth = self.get_input_tensor_shape()

        # The API returns all the output tensors flattened and concatenated. We
        # have to figure out the boundaries from the tensor shapes & sizes.
        offset = 0
        self._output_offsets = [0]
        for size in self.get_all_output_tensors_sizes():
            print(size)
            offset += size
            self._output_offsets.append(int(offset))

    def DetectPosesInImage(self, img):
        """Detects poses in a given image.

           For ideal results make sure the image fed to this function is close to the
           expected input size - it is the caller's responsibility to resize the
           image accordingly.

        Args:
          img: numpy array containing image
        """

        # Extend or crop the input to match the input shape of the network.
        if img.shape[0] < self.image_height or img.shape[1] < self.image_width:
            img = np.pad(img, [[0, max(0, self.image_height - img.shape[0])],
                               [0, max(0, self.image_width - img.shape[1])], [0, 0]],
                         mode='constant')
        img = img[0:self.image_height, 0:self.image_width]
        assert (img.shape == tuple(self._input_tensor_shape[1:]))
        # Run the inference (API expects the data to be flattened)
        return self.ParseOutput(self.run_inference(img.flatten()))

    def ParseOutput(self, output):
        inference_time, output = output

        return output, inference_time

```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.6

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, edgetpu api is deprecated. Can you please try with [pose_engine.py](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) from [project_posenet repo](https://github.com/google-coral/project-posenet).

**Comment by JiashuGuo** [comment]
> Hi, edgetpu api is deprecated. Can you please try with [pose_engine.py](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) from [project_posenet repo](https://github.com/google-coral/project-posenet).

Yeah, I tried the new pose_engine and got an new error:
```
Traceback (most recent call last):
  File "simple_pose.py", line 27, in <module>
    engine = PoseEngine('/home/dev/projects/compositeasr/asr_backend/src/retrainModel/out/semantic_segmentation/personlab/kp_short_edgetpu.tflite')
  File "/home/dev/projects/coral/project-posenet/pose_engine.py", line 78, in __init__
    posenet_decoder_delegate = load_delegate(POSENET_SHARED_LIB)
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: posenet_lib/x86_64/posenet_decoder.so: cannot open shared object file: No such file or directory
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0x7f97172ca828>>
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

```

**Comment by hjonnala** [comment]
can you please try to replace the custom posenet lib path [here](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py#L32) and try the script.

**Comment by JiashuGuo** [comment]
> can you please try to replace the custom posenet lib path [here](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py#L32) and try the script.

What do you mean by replacing the custom posenet lib path? I didn't change the path from the original script, not sure what is the correct path for that lib. If I change that line to `POSENET_SHARED_LIB = 'posenet_decoder.so'` I got:
```
Traceback (most recent call last):
  File "simple_pose.py", line 27, in <module>
    engine = PoseEngine('/home/dev/projects/compositeasr/asr_backend/src/retrainModel/out/semantic_segmentation/personlab/kp_short_edgetpu.tflite')
  File "/home/dev/projects/coral/project-posenet/pose_engine.py", line 77, in __init__
    posenet_decoder_delegate = load_delegate(POSENET_SHARED_LIB)
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: posenet_decoder.so: cannot open shared object file: No such file or directory
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0x7fb1b252ce10>>
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
```

**Comment by hjonnala** [comment]
I am not able to run the tflite model.. can you please share the tflite code that you are able to run this model.

```
 python3 /home/hemanthreddyj/snippets/posenet/test_decoder_inference.py
/home/hemanthreddyj/Downloads/kp_short.tflite
Traceback (most recent call last):
  File "/home/hemanthreddyj/snippets/posenet/test_decoder_inference.py", line 24, in <module>
    interpreter.allocate_tensors()
  File "/home/hemanthreddyj/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 5 (FlexFusedBatchNormV3) failed to prepare.
```

**Comment by JiashuGuo** [comment]
> I am not able to run the tflite model.. can you please share the tflite code that you are able to run this model.
> 
> ```
>  python3 /home/hemanthreddyj/snippets/posenet/test_decoder_inference.py
> /home/hemanthreddyj/Downloads/kp_short.tflite
> Traceback (most recent call last):
>   File "/home/hemanthreddyj/snippets/posenet/test_decoder_inference.py", line 24, in <module>
>     interpreter.allocate_tensors()
>   File "/home/hemanthreddyj/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
>     return self._interpreter.AllocateTensors()
> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 5 (FlexFusedBatchNormV3) failed to prepare.
> ```

Here is the code I run the tflite model:
```
import numpy as np
import tensorflow.compat.v1 as tf
from PIL import Image
print(tf.__version__)

def run_tflite_model(tflite_file, input_data):
  
  # Initialize the interpreter
  interpreter = tf.lite.Interpreter(model_path=str(tflite_file))
  interpreter.allocate_tensors()

  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()

  input_shape = input_details[0]['shape']

  input_data = np.asarray(input_data).reshape(1, 401, 401, 3)
  interpreter.set_tensor(input_details[0]['index'], input_data)

  interpreter.invoke()

  kp_maps = interpreter.get_tensor(output_details[0]['index'])
  short_offsets = interpreter.get_tensor(output_details[1]['index'])
  mid_offsets = interpreter.get_tensor(output_details[2]['index'])

  print(tf.shape(kp_maps), tf.shape(short_offsets), tf.shape(mid_offsets))
  return [kp_maps, short_offsets, mid_offsets]

input_data = Image.open('couple.jpg')
output_file='path/to/kp_short.tflite'
predictions = run_tflite_model(output_file, input_data)
```

**Comment by JiashuGuo** [comment]
And here is the link for compiled edgetpu model: [https://drive.google.com/file/d/1OuGu05H2QwuJhMPQU3KIDp44kLSTSDSS/view?usp=sharing](url)

**Comment by hjonnala** [comment]
Hi, please try this [script](https://github.com/hjonnala/snippets/blob/main/edgetpu_504/test_inference.py) to run inference..As your model output looks different from this [model](https://github.com/google-coral/project-posenet/blob/master/simple_pose.py#L26) you might to have to write your own [pose_engine.py](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) script with pycoral.

**Comment by JiashuGuo** [comment]
> Hi, please try this [script](https://github.com/hjonnala/snippets/blob/main/edgetpu_504/test_inference.py) to run inference..As your model output looks different from this [model](https://github.com/google-coral/project-posenet/blob/master/simple_pose.py#L26) you might to have to write your own [pose_engine.py](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) script with pycoral.

I actually tried to write a script that uses `tflite.Interpreter(model_path=str(tflite_file)` to run the model, and it seems the inference ended up with "Python Core dumped" error.

**Comment by hjonnala** [comment]
for edgetpu models please include [experimental delegates](https://github.com/hjonnala/snippets/blob/main/edgetpu_504/test_inference.py#L9) to run the inference.

**Comment by JiashuGuo** [comment]
> for edgetpu models please include [experimental delegates](https://github.com/hjonnala/snippets/blob/main/edgetpu_504/test_inference.py#L9) to run the inference.

Tried the script and got:
```
Traceback (most recent call last):
  File "run_poseNet.py", line 30, in <module>
    interpreter.allocate_tensors()
  File "/home/dev/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: 98693676Node number 1746 (EdgeTpuDelegateForCustomOp) failed to prepare.
```

**Comment by hjonnala** [comment]
Hmm.. Is it the same model you are running? I don't find **EdgeTpuDelegateForCustomOp** in kp_short_edgetpu model.

can you please share the following info:
```

Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import tflite_runtime as tflite
>>> import pycoral
>>> from pycoral.utils.edgetpu import get_runtime_version
>>> get_runtime_version()
'BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)'
>>> numpy.__version__
'1.19.5'
>>> tflite.__version__
'2.5.0.post1'
>>> pycoral.__version__
'2.0.0'
>>> 

```

**Comment by JiashuGuo** [comment]
> Hmm.. Is it the same model you are running? I don't find **EdgeTpuDelegateForCustomOp** in kp_short_edgetpu model.
> 
> can you please share the following info:
> 
> ```
> 
> Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy
> >>> import tflite_runtime as tflite
> >>> import pycoral
> >>> from pycoral.utils.edgetpu import get_runtime_version
> >>> get_runtime_version()
> 'BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)'
> >>> numpy.__version__
> '1.19.5'
> >>> tflite.__version__
> '2.5.0.post1'
> >>> pycoral.__version__
> '2.0.0'
> >>> 
> ```

Yes, it is the kp_short_edgetpu.tflite model. Here is the output: 
```
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import tflite_runtime as tflite
>>> import pycoral
>>> from pycoral.utils.edgetpu import get_runtime_version
>>> get_runtime_version()
'BuildLabel(COMPILER=5.4.0 20160609,DATE=redacted,TIME=redacted,CL_NUMBER=317268237), RuntimeVersion(13)'
>>> numpy.__version__
'1.18.5'
IndentationError: unexpected indent
>>> tflite.__version__
'2.5.0.post1'
>>> pycoral.__version__
'2.0.0'
>>>
> 
```

**Comment by hjonnala** [comment]
please upgrade the edgetpu runtime to RuntimeVersion(14) and try the script.

```
sudo apt-get update

sudo apt-get dist-upgrade
```

**Comment by JiashuGuo** [comment]
> please upgrade the edgetpu runtime to RuntimeVersion(14) and try the script.
> 
> ```
> sudo apt-get update
> 
> sudo apt-get dist-upgrade
> ```

The script is able to run after upgrading the run_time to version 14, though it takes a super long time to finish. But I think this issue is solved, thanks for helping. 
For others' reference, I upgrade run_time following this link: [https://coral.ai/software/#debian-packages](url), since `sudo apt-get dist-upgrade` doesn't work.
