### ISSUE TITLE
Mac OSX 12 Monterey. unable to install PyCoral library

### ISSUE THREAD

**Issue by paloj** [google-coral/edgetpu#539]
### Description

Following install instructions here: https://coral.ai/docs/accelerator/get-started/#2-install-the-pycoral-library
I get stuck on 2b:
python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0
gives error:
ERROR: Could not find a version that satisfies the requirement pycoral~=2.0 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9)
ERROR: No matching distribution found for pycoral~=2.0

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mac OS

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

```shell
python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
ERROR: Could not find a version that satisfies the requirement pycoral~=2.0 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9)
ERROR: No matching distribution found for pycoral~=2.0
```
</details>

**Comment by hjonnala** [comment]
@paloj can you please try to install [tflite runtime](https://github.com/google-coral/pycoral/releases/) and pycoral in the same order from the whl flles: https://coral.ai/software/#pycoral-api.. Thanks!

**Comment by felisida** [comment]
I followed the whole procedure, without displaying any errors, but when I tried to run the example I get this error

Traceback (most recent call last):
  File "/Users/homeassistant/coral/pycoral/examples/classify_image.py", line 40, in <module>
    from pycoral.utils.edgetpu import make_interpreter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/pybind/_pywrap_coral.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libedgetpu.1.dylib'
  Referenced from: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/pybind/_pywrap_coral.cpython-39-darwin.so'
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/pybind/libedgetpu.1.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/pybind/libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file)

thi is the last part of procedure
homeassistant@IMAC-4A7A7E ~ % python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0                                                                         
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
Collecting pycoral~=2.0
  Downloading https://github.com/google-coral/pycoral/releases/download/v2.0.0/pycoral-2.0.0-cp39-cp39-macosx_10_15_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 2.5 MB/s 
Requirement already satisfied: Pillow>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pycoral~=2.0) (10.0.0)
Requirement already satisfied: tflite-runtime==2.5.0.post1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pycoral~=2.0) (2.5.0.post1)
Requirement already satisfied: numpy>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pycoral~=2.0) (1.25.2)
Installing collected packages: pycoral
Successfully installed pycoral-2.0.0
WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --upgrade pip' command.

**Comment by tomscholz** [comment]
I am facing the same issue. Did anyone manage to get it running?

**Comment by hongyuejin** [comment]
same issue here

**Comment by tomscholz** [comment]
I solved it by upgrading to Ventura
