### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by vladmarian20005** [google-coral/edgetpu#569]
### Description

Hello! This isn't really an issue but a simple question! Is there any example code on how I can use edgetpu and the Coral USB Accelerator for live object detection using opencv(cv2.VideoCapture)?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mac OS

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
please check the  opencv example from examples-camera repo: https://github.com/google-coral/examples-camera/tree/master/opencv

**Comment by vladmarian20005** [comment]
I have tried running this code with the bird model given in the example codes and this is the error i get:

`Traceback (most recent call last):
  File "/Users/vladmarian/testcam/examples-camera/opencv/detect.py", line 99, in <module>
    main()
  File "/Users/vladmarian/testcam/examples-camera/opencv/detect.py", line 56, in main
    interpreter = make_interpreter(args.model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libedgetpu.1.dylib, 0x0006): tried: 'libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file), '/Users/vladmarian/libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file)
Exception ignored in: <function Delegate.__del__ at 0x110831550>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'`

My USB Accelerator is plugged in my computer. How should i fix this?

**Edit**: When i try running the example code, it works perfectly.

**Comment by vladmarian20005** [comment]
I have tried the same code with an object detection model from https://coral.ai/models and it seems like i get the same error: 

Loading ssd_mobilenet_v1_coco_quant_postprocess_edgetpu.tflite with coco_labels.txt labels.
Traceback (most recent call last):
  File "/Users/vladmarian/Desktop/CoralTest/detect.py", line 99, in <module>
    main()
  File "/Users/vladmarian/Desktop/CoralTest/detect.py", line 56, in main
    interpreter = make_interpreter(args.model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libedgetpu.1.dylib, 0x0006): tried: 'libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file), '/Users/vladmarian/Desktop/CoralTest/libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file)
Exception ignored in: <function Delegate.__del__ at 0x118bc5550>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

**Comment by hjonnala** [comment]
> OSError: dlopen(libedgetpu.1.dylib, 0x0006): tried: 'libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file), '/Users/vladmarian/libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file) Exception

To resolve this please try : sudo cp -r /usr/local/lib/libedgetpu* /Users/vladmarian/

> OSError: dlopen(libedgetpu.1.dylib, 0x0006): tried: 'libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file), '/Users/vladmarian/Desktop/CoralTest/libedgetpu.1.dylib' (no such file), '/usr/lib/libedgetpu.1.dylib' (no such file)

To resolve this please try : sudo cp -r /usr/local/lib/libedgetpu* /Users/vladmarian/Desktop/CoralTest/

To fix this issue permanently please try this option: https://github.com/google-coral/edgetpu/issues/568#issuecomment-1085072224

Thanks!

**Comment by vladmarian20005** [comment]
Thank You!! It works properly now!
