### ISSUE TITLE
Edge TPU access denied for new users on Coral Dev Board

### ISSUE THREAD

**Issue by youngsooroh** [google-coral/edgetpu#637]
Only the "mendel" user seems to have access privilege to the EdgeTPU.
I have been trying to run Posenet example on the coral dev board using another user rather than the default "mendel" user, but I was not able to do this yet. I wasn't able to find any resources on the web or any documentation about this topic. 

OS: Linux wishful-snail 4.14.98-imx #1 SMP PREEMPT Tue Nov 2 02:55:21 UTC 2021 aarch64 GNU/Linux
Mendel OS Image used: [enterprise-eagle-flashcard-20211117215217.zip](https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-flashcard-20211117215217.zip)

Steps to reproduce:
1. Create a new user named "test" and add it to the right groups (test adm sudo audio video plugdev staff games users netdev input render bluetooth i2c systemd-journal apex)
2. Download Posetnet example (https://github.com/google-coral/project-posenet) and run simple_pose.py using the "test" user

Throws the following exception:
Traceback (most recent call last): File "simple_pose.py", line 28, in poses, inference_time = engine.DetectPosesInImage(pil_image) File "/home/aims/git/project-posenet/pose_engine.py", line 127, in DetectPosesInImage self.run_inference(input_data.flatten()) File "/home/aims/git/project-posenet/pose_engine.py", line 102, in run_inference edgetpu.run_inference(self._interpreter, input_data) File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 206, in run_inference expected_input_size) RuntimeError: InvokeWithMemBuffer failed: Subgraph is already in use. Using an interpreter or a subgraph in multiple threads is not supported. Recursion in the graph is not supported.

However, the example script runs fine if I run the example using the "mendel" user.

**Comment by hjonnala** [comment]
Please try the below steps to run simple_pose.py with other user(mendel2):

```
mendel@deft-goose:~$ sudo adduser mendel2
Adding user `mendel2' ...
Adding new group `mendel2' (1002) ...
Adding new user `mendel2' (1001) with group `mendel2' ...
Creating home directory `/home/mendel2' ...
Copying files from `/etc/skel' ...
New password: 
Retype new password: 
passwd: password updated successfully
Changing the user information for mendel2
Enter the new value, or press ENTER for the default
        Full Name []: 
        Room Number []: 
        Work Phone []: 
        Home Phone []: 
        Other []: 
Is the information correct? [Y/n] y
```
`mendel@deft-goose:~$ sudo usermod -aG sudo mendel2`

`mendel@deft-goose:~$ sudo su mendel2`

```
mendel2@deft-goose:/home/mendel$ cd project-posenet/
mendel2@deft-goose:/home/mendel/project-posenet$ sudo python3 simple_pose.py 

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for mendel2: 
Sorry, try again.
[sudo] password for mendel2: 
--2022-08-05 18:08:37--  https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hindu_marriage_ceremony_offering.jpg/640px-Hindu_marriage_ceremony_offering.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.154.240, 2620:0:861:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.154.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83328 (81K) [image/jpeg]
Saving to: ‘/tmp/couple.jpg’

/tmp/couple.jpg                                           100%[=====================================================================================================================================>]  81.38K  --.-KB/s    in 0.06s   

2022-08-05 18:08:38 (1.30 MB/s) - ‘/tmp/couple.jpg’ saved [83328/83328]

Inference time: 17 ms

Pose Score:  0.60673916
  NOSE                 x=210  y=152  score=1.0
  LEFT_EYE             x=223  y=138  score=1.0
  RIGHT_EYE            x=199  y=137  score=1.0
  LEFT_EAR             x=244  y=135  score=1.0
  RIGHT_EAR            x=183  y=129  score=0.8
  LEFT_SHOULDER        x=269  y=169  score=0.8
  RIGHT_SHOULDER       x=160  y=174  score=1.0
  LEFT_ELBOW           x=281  y=255  score=0.6
  RIGHT_ELBOW          x=153  y=253  score=0.9
  LEFT_WRIST           x=237  y=332  score=0.6
  RIGHT_WRIST          x=163  y=304  score=0.5
  LEFT_HIP             x=261  y=317  score=0.1
  RIGHT_HIP            x=173  y=309  score=0.1
  LEFT_KNEE            x=223  y=339  score=0.3
  RIGHT_KNEE           x=200  y=342  score=0.3
  LEFT_ANKLE           x=186  y=407  score=0.1
  RIGHT_ANKLE          x=188  y=410  score=0.2

Pose Score:  0.54908466
  NOSE                 x=400  y=145  score=1.0
  LEFT_EYE             x=418  y=129  score=1.0
  RIGHT_EYE            x=383  y=127  score=1.0
  LEFT_EAR             x=458  y=110  score=0.9
  RIGHT_EAR            x=371  y=121  score=0.2
  LEFT_SHOULDER        x=496  y=168  score=1.0
  RIGHT_SHOULDER       x=361  y=150  score=0.8
  LEFT_ELBOW           x=463  y=291  score=1.0
  RIGHT_ELBOW          x=331  y=245  score=0.8
  LEFT_WRIST           x=340  y=305  score=0.9
  RIGHT_WRIST          x=234  y=332  score=0.5
  LEFT_HIP             x=485  y=312  score=0.1
  RIGHT_HIP            x=364  y=327  score=0.1
  LEFT_KNEE            x=470  y=336  score=0.0
  RIGHT_KNEE           x=245  y=329  score=0.1
  LEFT_ANKLE           x=444  y=381  score=0.0
  RIGHT_ANKLE          x=188  y=410  score=0.2
mendel2@deft-goose:/home/mendel/project-posenet$ 
```
Ref: https://www.freecodecamp.org/news/the-ultimate-guide-to-linux-creating-a-sudo-user/

**Comment by youngsooroh** [comment]
@hjonnala Thanks for the update. 

It's not the perfect solution since you need to run the script as sudo, nonetheless, better than nothing since I can at least make use of the EdgeTPU. I do still think that we should be able to run the script without sudo privilege as you can do with the "mendel" user.

Regards,

**Comment by hjonnala** [comment]
To run without sudo, 
try adding the below groups to new user:

```
mendel2@deft-goose:/home/mendel/project-posenet$ groups mendel2
mendel2 : mendel2 root sudo mendel apex
```

and add the below line to at the end of `sudo visudo /etc/sudoers `file:
`mendel2 ALL=(ALL) NOPASSWD: ALL`
 
and reboot the device.

```
mendel2@deft-goose:/home/mendel/project-posenet$ python3 simple_pose.py 
--2022-08-08 22:23:46--  https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hindu_marriage_ceremony_offering.jpg/640px-Hindu_marriage_ceremony_offering.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.154.240, 2620:0:861:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.154.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83328 (81K) [image/jpeg]
Saving to: ‘/tmp/couple.jpg’

/tmp/couple.jpg                                           100%[=====================================================================================================================================>]  81.38K  --.-KB/s    in 0.07s   

2022-08-08 22:23:46 (1.15 MB/s) - ‘/tmp/couple.jpg’ saved [83328/83328]

Inference time: 20 ms

Pose Score:  0.60673916

```

**Comment by youngsooroh** [comment]
@hjonnala It works, thanks.
