### ISSUE TITLE
Second TPU on dual M.2 Accelerator not working, Failed to load delegate from libedgetpu.so.1

### ISSUE THREAD

**Issue by tehniemer** [google-coral/edgetpu#641]
### Description

I have a dual TPU M.2 accelerator, both devices are seen by the system and the first device is working properly in [Frigate](https://github.com/blakeblackshear/frigate), but the second device is not. When I run the test from the [Getting Started](https://coral.ai/docs/m2/get-started/#pycoral-on-win) page I see a similar error to what I was experiencing [here](https://github.com/google-coral/edgetpu/issues/611), but that fix is still in place.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

M.2 Accelerator with dual Edge TPU

### Relevant Log Output

```shell
root@nvr:~/coral/pycoral# lspci -nn | grep 089a
04:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
05:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```
```
root@nvr:~/coral/pycoral# python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_                                                     labels.txt --input test_data/parrot.jpg
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I tflite/edgetpu_context_direct.cc:106] USB always DFU: False (default)
I tflite/edgetpu_context_direct.cc:128] USB bulk-in queue capacity: default
I tflite/edgetpu_context_direct.cc:67] Performance expectation: Max (default)
I ./driver/mmio/host_queue.h:266] Starting in normal mode
I driver/kernel/kernel_registers.cc:83] Opening /dev/apex_0. read_only=0
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000040000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7f72b4877000
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000044000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7f72b4876000
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000048000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7f72b4875000
I driver/kernel/kernel_registers.cc:211] Read: offset = 0x00000000000486f0, value: = 0x0000000000000000
I driver/kernel/kernel_registers.cc:190] Write: offset = 0x00000000000487a8, value = 0x0000000000000000
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000040000, mmap_size=4096, read_only=0
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000044000, mmap_size=4096, read_only=0
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000048000, mmap_size=4096, read_only=0
I tflite/edgetpu_context_direct.cc:401] Failed to open device [Apex (PCIe)] at [/dev/apex_0]: Failed precondition: Could not partition page table. : 5 (Device o                                                     r resource busy)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/coral/pycoral/examples/classify_image.py", line 122, in <module>
    main()
  File "/root/coral/pycoral/examples/classify_image.py", line 72, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```
```
</details>

**Comment by hjonnala** [comment]
can you please share the output of below command. Thanks!

- `lspci -vvv|grep -i MSI-X`

**Comment by tehniemer** [comment]
```
root@nvr:~# lspci -vvv|grep -i MSI-X
Capabilities: [b0] MSI-X: Enable+ Count=4 Masked-
Capabilities: [d0] MSI-X: Enable+ Count=128 Masked-
Capabilities: [d0] MSI-X: Enable+ Count=128 Masked-
pcilib: sysfs_read_vpd: read failed: Input/output error
Capabilities: [b0] MSI-X: Enable+ Count=9 Masked-
```

**Comment by tehniemer** [comment]
@hjonnala, do you have any next steps?

**Comment by hjonnala** [comment]
Seems to be issue with host system configuration, not sure how to fix it. Can you try this example without frigate container on your host machine: https://github.com/google-coral/pycoral/blob/master/examples/model_pipelining_classify_image.py

**Comment by tehniemer** [comment]
It's odd, because at one point both tpus were working in Frigate. 

Here's the output from trying to run that model on the host machine:
```
root@nvr:~/coral/pycoral# python3 examples/model_pipelining_classify_image.py   --models     test_data/pipeline/inception_v3_299_quant_segment_%d_of_2_edgetpu.tflite   --labels test_data/imagenet_labels.txt   --input test_data/parrot.jpg
Using devices:  ['pci:0', 'pci:1']
Using models:  ['test_data/pipeline/inception_v3_299_quant_segment_0_of_2_edgetpu.tflite', 'test_data/pipeline/inception_v3_299_quant_segment_1_of_2_edgetpu.tflite']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/coral/pycoral/examples/model_pipelining_classify_image.py", line 172, in <module>
    main()
  File "/root/coral/pycoral/examples/model_pipelining_classify_image.py", line 132, in main
    runner = _make_runner(model_paths, devices)
  File "/root/coral/pycoral/examples/model_pipelining_classify_image.py", line 85, in _make_runner
    interpreters = [make_interpreter(m, d) for m, d in zip(model_paths, devices)]
  File "/root/coral/pycoral/examples/model_pipelining_classify_image.py", line 85, in <listcomp>
    interpreters = [make_interpreter(m, d) for m, d in zip(model_paths, devices)]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

**Comment by tehniemer** [comment]
I swapped the card into another machine, and everything works as expected. I then moved the card back to the original machine, but in a different slot and it worked as expected. Then I moved it back to the original slot and the problem is back. 

Another tidbit of information is that when I moved to a different slot in the same machine my network adapter was renamed, and I lost all network access.

Are there any other ideas?

**Comment by tehniemer** [comment]
I was able to get both working again by removing the associated PCI devices and rescanning, however, this fix does not survive a reboot.
```
root@nvr:~# lspci -PP
00:00.0 Host bridge: Intel Corporation Device 3e0f (rev 08)
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-S GT1 [UHD Graphics 610]
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:14.5 SD Host controller: Intel Corporation Device a375 (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:15.1 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #1 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake PCH SATA AHCI Controller (rev 10)
00:1c.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #5 (rev f0)
00:1c.7 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #8 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1e.0 Communication controller: Intel Corporation Cannon Lake PCH Serial IO UART Host Controller (rev 10)
00:1f.0 ISA bridge: Intel Corporation H370 Chipset LPC/eSPI Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
00:1c.0/01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
00:1c.7/02:00.0 PCI bridge: ASMedia Technology Inc. Device 1182
00:1c.7/02:00.0/03:03.0 PCI bridge: ASMedia Technology Inc. Device 1182
00:1c.7/02:00.0/03:07.0 PCI bridge: ASMedia Technology Inc. Device 1182
00:1c.7/02:00.0/03:03.0/04:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
00:1c.7/02:00.0/03:07.0/05:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
00:1d.0/06:00.0 Non-Volatile memory controller: Shenzhen Longsys Electronics Co., Ltd. Device 1d97 (rev 01)
```
```
echo 1 >/sys/bus/pci/devices/0000:00:1c.7/remove
```
```
echo 1 >/sys/bus/pci/rescan
```

**Comment by tehniemer** [comment]
> Seems to be issue with host system configuration, not sure how to fix it. Can you try this example without frigate container on your host machine: https://github.com/google-coral/pycoral/blob/master/examples/model_pipelining_classify_image.py

I think I misunderstood your request here. 

I figured out the problem I was having wasn't really a problem after all, turns out the host machine can't use a PCI device that has been passed into a docker container. Once I realized that I determined everything is working properly.
