### ISSUE TITLE
EfficientDet Lite 2 Model on Raspberry Pi and Coral Edge TPU | ValueError: Object detection models require TFLite Model Metadata but none was found

### ISSUE THREAD

**Issue by ghbn8** [google-coral/edgetpu#652]
### Description

I have downloaded the standard EfficientDet Lite 2 model (with metadata) from Tensorflow Hub [https://tfhub.dev/s?deployment-format=lite&module-type=image-object-detection&tf-version=tf2](url), compiling with the provided Google Colab notebook [https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb#scrollTo=joxrIB0I3cdi](url), and deploying to a Raspberry Pi 3B+ with a connected Google Coral Edge TPU.

When attempting to run the below self contained Python script, I am receiving the following error:
_Traceback (most recent call last):
  File "video_object_detection_run_on_pi.py", line 98, in <module>
    detector = vision.ObjectDetector.create_from_options(options)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_lite_support/python/task/vision/object_detector.py", line 83, in create_from_options
    options.detection_options)
ValueError: Object detection models require TFLite Model Metadata but none was found_

Can you please advise me on the proper way to address this lack of metadata?

No modifications have been made to the model and I am experiencing the exact same problem with EfficientDet Lite 0 and 1 models.

Running Python 3.7.3 on Raspberry Pi 3B+ with Google Coral Edge TPU
`
model = '082822_am.tflite' #str
camera_id = 'video_4.avi' #int for webcams or string for video file
width = 640 #int
height = 480 #int
num_threads = 4 #int
enable_edgetpu = False #bool

# Visualization parameters
row_size = 20  # pixels
margin = 24  # pixels
left_margin = margin
text_color = (0, 0, 255)  # red
font_size = 1
font_thickness = 1
fps_avg_frame_count = 10

distance_threshold = 260 # currently in pixel values (480 is the bottom of the camera, 0 is the top)
stop_text_location = (300, 50)

path = 'frames_with_obstacles/'

def visualize(
    image: np.ndarray,
    detection_result: processor.DetectionResult,
) -> np.ndarray:

  for detection in detection_result.detections:
    # Draw bounding_box
    bbox = detection.bounding_box
    start_point = bbox.origin_x, bbox.origin_y
    end_point = bbox.origin_x + bbox.width, bbox.origin_y + bbox.height
    cv2.rectangle(image, start_point, end_point, text_color, 3)

    # Draw label and score
    category = detection.classes[0]
    class_name = category.class_name
    probability = round(category.score, 2)
    result_text = class_name + ' (' + str(probability) + ')'
    text_location = (margin + bbox.origin_x,
                     margin + row_size + bbox.origin_y)
    cv2.putText(image, result_text, text_location, cv2.FONT_HERSHEY_PLAIN,
                font_size, text_color, font_thickness)
                
    # Display stop message if object is too close
    if (bbox.origin_y + bbox.height) > distance_threshold:
        print(' OBJECT TOO CLOSE STOP ')
        cv2.putText(image, 'STOP', stop_text_location, cv2.FONT_HERSHEY_PLAIN,
                font_size, text_color, font_thickness)
    else: pass

  return image

# Start capturing video input from the camera
cap = cv2.VideoCapture(camera_id)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, width)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

# Initialize the object detection model
base_options = core.BaseOptions(file_name=model, use_coral=enable_edgetpu, num_threads=num_threads)
detection_options = processor.DetectionOptions(max_results=3, score_threshold=0.3)
options = vision.ObjectDetectorOptions(base_options=base_options, detection_options=detection_options)

detector = vision.ObjectDetector.create_from_options(options)

# Continuously capture images from the camera and run inference
while cap.isOpened():
    success, image = cap.read()
    if not success:
      sys.exit(
          'ERROR: Unable to read from webcam. Please verify your webcam settings.'
      )

    counter += 1
    image = cv2.flip(image, 1)

    # Convert the image from BGR to RGB as required by the TFLite model.
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Create a TensorImage object from the RGB image.
    input_tensor = vision.TensorImage.create_from_array(rgb_image)

    # Run object detection estimation using the model.
    detection_result = detector.detect(input_tensor)
    
    for detection in detection_result.detections:
        image = visualize(image, detection_result)
        
    cv2.rectangle(image, (0,distance_threshold), (width,distance_threshold), text_color, 3)
    

    # Stop the program if the ESC key is pressed.
    if cv2.waitKey(1) == 27:
      break
      cap.release()
      cv2.destroyAllWindows()
      
    cv2.imshow('object_detector', image)
    
    
cap.release()
cv2.destroyAllWindows()`

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.7

### Relevant Log Output

```shell
Edge TPU Compiler version 16.0.384591198
Input: efficientdet_lite2.tflite
Output: efficientdet_lite2_edgetpu.tflite

Operator                       Count      Status

CONV_2D                        128        Mapped to Edge TPU
DEQUANTIZE                     2          Operation is working on an unsupported data type
RESIZE_NEAREST_NEIGHBOR        20         Mapped to Edge TPU
DEPTHWISE_CONV_2D              101        Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  1          Mapped to Edge TPU
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        7          Mapped to Edge TPU
ADD                            69         Mapped to Edge TPU
CUSTOM                         1          Operation is working on an unsupported data type
MAX_POOL_2D                    22         Mapped to Edge TPU
QUANTIZE                       1          Mapped to Edge TPU
```
</details>

**Comment by ghbn8** [comment]
While it is not required to have a labels.txt file to run a tflite model on the CPU, the example python script for the TPU does require a label text file (or "metadata").
