### ISSUE TITLE
ValueError('Failed to load delegate from {}\n{}'.format( ValueError: Failed to load delegate from edgetpu.dll)

### ISSUE THREAD

**Issue by ary1111** [google-coral/edgetpu#694]
### Description

Just purchased a Coral USB Accelerator and cannot run the demo on a Windows 11, Mac, or Raspberry Pi machine. Once we installed 20221024 runtime and PyCoral library, we cloned the GitHub repository. When we try to run the example, we get the following error on Windows 11:

```
Traceback (most recent call last):
  File "C:\Users\acct\AppData\Local\Programs\Python\Python39\lib\site-packages\tflite_runtime\interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Users\acct\AppData\Local\Programs\Python\Python39\lib\site-packages\tflite_runtime\interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\acct\Documents\GitHub\pycoral\examples\classify_image.py", line 121, in <module>
    main()
  File "C:\Users\acct\Documents\GitHub\pycoral\examples\classify_image.py", line 71, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "C:\Users\acct\AppData\Local\Programs\Python\Python39\lib\site-packages\pycoral\utils\edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "C:\Users\acct\AppData\Local\Programs\Python\Python39\lib\site-packages\pycoral\utils\edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "C:\Users\acct\AppData\Local\Programs\Python\Python39\lib\site-packages\tflite_runtime\interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from edgetpu.dll
```

Received similar errors in the mac and raspberry pi environments. I do not see Coral USB listed once performing the install

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi can you please try  the demo adding  the  below lines at: https://github.com/google-coral/pycoral/blob/master/examples/classify_image.py#L41 and share the logs..Thanks!

```
from pycoral.pybind._pywrap_coral import SetVerbosity as set_verbosity
set_verbosity(10)
```

**Comment by ary1111** [comment]
Here are our logs from a Raspberry Pi 4:
```
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/driver_factory_default.cc:31] Failed to open /sys/class/apex: No such file or directory
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I tflite/edgetpu_manager_direct.cc:471] No device of type Apex (PCIe) is available.
I tflite/edgetpu_manager_direct.cc:471] No device of type Apex (USB) is available.
I tflite/edgetpu_manager_direct.cc:471] No device of type Apex (Reference) is available.
I tflite/edgetpu_manager_direct.cc:502] Failed allocating Edge TPU device for shared ownership.
Traceback (most recent call last):
  File "/home/user/project/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/user/project/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/coral/pycoral_test/examples/classify_image.py", line 122, in <module>
    main()
  File "/home/user/coral/pycoral_test/examples/classify_image.py", line 72, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/home/user/project/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/home/intelligentmedicine/circulate/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/home/user/project/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

**Comment by hjonnala** [comment]
Thanks for the logs. Does the LED light is on USB accelartor? Please share the output of `lsusb` command.

**Comment by SeanyTea** [comment]
Here is the output from `lsusb` command:

`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

The LED light is on but it blinks.

**Comment by hjonnala** [comment]
It should blink when running the Edgetpu Model. The device is defective since its blinking without running any TPU model and not listed under `lsusb`, please return the product to original seller and get the new one. Thanks!
