### ISSUE TITLE
cant start with my Dev Board | no content displayed after entering ”mdt devices“

### ISSUE THREAD

**Issue by loiswen** [google-coral/edgetpu#730]
### Description

Dev Board+System：Ubuntu20.05 in virturalbox7.0.6（host：win10）
I followed this tutorial:[1](https://coral.ai/docs/dev-board/get-started/#flash-the-board); but got stuck at step 4, after I plugged the Dev Board into the computer, typing the commands（”mdt devices“/“mdt wait-for-device”） in the tutorial in the virtual machine only showed the following display, there was no " board hostname" , only this
![捕获](https://user-images.githubusercontent.com/47554331/225635290-be29fa07-3837-47aa-b897-70ff98d77ef5.JPG)

Is there something I did wrong? What should I do next?
I am still a newbie and very eager if you can give me help
thank alot

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Ubuntu

### Coral Device

Dev Board

### Programming Language

Python 3.8

### Relevant Log Output

```shell
wenhr@wenhr-VirtualBox:~$ mdt devices
wenhr@wenhr-VirtualBox:~$ mdt wait-for-device
Waiting for device...
Traceback (most recent call last):
  File "/home/wenhr/.local/bin/mdt", line 8, in <module>
  File "/home/wenhr/.local/lib/python3.8/site-packages/mdt/main.py", line 162, in main
  File "/home/wenhr/.local/lib/python3.8/site-packages/mdt/devices.py", line 71, in run
  File "/home/wenhr/.local/lib/python3.8/site-packages/mdt/discoverer.py", line 40, in discover
  File "/home/wenhr/.local/lib/python3.8/site-packages/zeroconf/_core.py", line 450, in __init__
  File "/home/wenhr/.local/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 360, in create_sockets
  File "/home/wenhr/.local/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 151, in normalize_interface_choice
  File "/home/wenhr/.local/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 74, in get_all_addresses
  File "/home/wenhr/.local/lib/python3.8/site-packages/ifaddr/_posix.py", line 56, in get_adapters
OSError: [Errno 24] Too many open files
wenhr@wenhr-VirtualBox:~$
```
</details>

**Comment by hjonnala** [comment]
Hi, 

- Have you tried the tutroial on native windows? 
- Is there is any reason you are using virtual box instead native OS? 
- Have you setup the [virtualbox](https://www.eltima.com/article/virtualbox-usb-passthrough/#:~:text=Plug%20the%20required%20USB%20device,appear%20in%20your%20guest%20OS.) to access local usb devices?

**Comment by menmazqj** [comment]
> Hi,
> 
> * Have you tried the tutroial on native windows?
> * Is there is any reason you are using virtual box instead native OS?
> * Have you setup the [virtualbox](https://www.eltima.com/article/virtualbox-usb-passthrough/#:~:text=Plug%20the%20required%20USB%20device,appear%20in%20your%20guest%20OS.) to access local usb devices?

Hi, hjonnala

I got the same problem with @loiswen. 

I followed the tutorial step by step with native Ubuntu20.04 OS. The first time I came up with the "mdt shows nothing" problem,   I reflash the board with lastest version Mentel Linux provided in tutorial page. With the red LED turned off, I thought I succeed to flashing my board. However, I can't connect it with mdt tool. Then, I tryed to connect the board via console. It failed too,

So, any ideas about my problem? @hjonnala
