### ISSUE TITLE
Connect a camera to the Dev Board - example fails with No module named 'OpenGL_accelerate'

### ISSUE THREAD

**Issue by Felix-Tr** [google-coral/edgetpu#750]
### Description

I encounter problems running the _edgetpuvision_ example from the [Tutorials](https://coral.ai/docs/dev-board/camera/).
When I initially flashed the dev board it worked, after flashing it again following the [Reflash Documentation](https://coral.ai/docs/dev-board/reflash/) I encountered the provided error that _OpenGL_accelerate_ is missing.

I only found the following related Issue #52 related to my problem but `pip3 install PyOpenGL-accelerate` also fails.

I run 

```
sudo apt-get update
sudo apt-get dist-upgrade
```

but needed to add the public key from the Google Cloud repository to sucessfully update and upgrade:

```
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
```

Output for `pip3 install PyOpenGL-accelerate` : 

```
Collecting PyOpenGL-accelerate
  Downloading https://files.pythonhosted.org/packages/8e/47/64aa665af0f7d0c2f6c4a865c1d521c3697504da971366d4dea12ce8b339/PyOpenGL-accelerate-3.1.6.tar.gz (550kB)
    100% |████████████████████████████████| 552kB 630kB/s 
Building wheels for collected packages: PyOpenGL-accelerate
  Running setup.py bdist_wheel for PyOpenGL-accelerate ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-4tr_apga --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/OpenGL_accelerate
  copying OpenGL_accelerate/__init__.py -> build/lib.linux-aarch64-3.7/OpenGL_accelerate
  running build_ext
  building 'OpenGL_accelerate.wrapper' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/src
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/.. -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/src -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate -I/usr/include/python3.7m -c src/wrapper.c -o build/temp.linux-aarch64-3.7/src/wrapper.o
  src/wrapper.c:6:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyOpenGL-accelerate
  Running setup.py clean for PyOpenGL-accelerate
Failed to build PyOpenGL-accelerate
Installing collected packages: PyOpenGL-accelerate
  Running setup.py install for PyOpenGL-accelerate ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-o6qf7z2t/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.7
    creating build/lib.linux-aarch64-3.7/OpenGL_accelerate
    copying OpenGL_accelerate/__init__.py -> build/lib.linux-aarch64-3.7/OpenGL_accelerate
    running build_ext
    building 'OpenGL_accelerate.wrapper' extension
    creating build/temp.linux-aarch64-3.7
    creating build/temp.linux-aarch64-3.7/src
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/.. -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/src -I/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate -I/usr/include/python3.7m -c src/wrapper.c -o build/temp.linux-aarch64-3.7/src/wrapper.o
    src/wrapper.c:6:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-o6qf7z2t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-gsvbarkl/PyOpenGL-accelerate/
```

Output for `cat /etc/os-release`:

```
PRETTY_NAME="Mendel GNU/Linux 5 (Eagle)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.ai/"
SUPPORT_URL="https://coral.ai/"
BUG_REPORT_URL="https://coral.ai/"
VERSION_CODENAME="eagle"
```

Output for `sudo lshw -short`:

```
H/W path  Device  Class      Description
========================================
                  system     Freescale i.MX8MQ Phanbell
/0                bus        Motherboard
/0/0              processor  cpu
/0/1              processor  cpu
/0/2              processor  cpu
/0/3              processor  cpu
/0/4              processor  idle-states
/0/5              processor  l2-cache0
/0/6              memory     985MiB System memory
/0/100            bridge     Synopsys, Inc.
/0/100/0  p2p0    network    QCA6174 802.11ac Wireless Network Adapter
/0/101            bridge     Synopsys, Inc.
/0/101/0          generic    Non-VGA unclassified device
/0/7              generic    Virtual I/O device
/1        usb1    bus        xHCI Host Controller
/2        usb2    bus        xHCI Host Controller
/3        usb0    network    Ethernet interface
/4        wlan0   network    Wireless interface
/5        eth0    network    Ethernet interface

```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Build/Install, Documentation Bug

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

```shell
edgetpu_classify_server --model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite --labels ${DEMO_FILES}/imagenet_labels.txt
INFO:edgetpuvision.streaming.server:Listening on ports tcp: 4665, web: 4664, annexb: 4666
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51594
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51594] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51594] Tx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51602
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51594] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51594] Stopped.
INFO:edgetpuvision.streaming.server:[192.168.178.43:51602] Rx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51614
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51614] Rx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51630
INFO:edgetpuvision.streaming.server:[192.168.178.43:51614] Tx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 3
INFO:edgetpuvision.streaming.server:[192.168.178.43:51614] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51630] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51614] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51636
INFO:edgetpuvision.streaming.server:Number of active clients: 3
INFO:edgetpuvision.streaming.server:[192.168.178.43:51636] Rx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51650
INFO:edgetpuvision.streaming.server:[192.168.178.43:51636] Tx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 4
INFO:edgetpuvision.streaming.server:[192.168.178.43:51636] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51650] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51636] Stopped.
INFO:edgetpuvision.streaming.server:[192.168.178.43:51650] Tx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 3
INFO:edgetpuvision.streaming.server:[192.168.178.43:51602] Tx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51650] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51650] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51602] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51602] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51666
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51666] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51666] Tx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51630] Tx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51666] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51666] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51630] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51630] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 0
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51678
INFO:edgetpuvision.streaming.server:[192.168.178.43:51678] Rx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51678] Tx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51686
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51678] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51686] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51678] Stopped.
INFO:edgetpuvision.streaming.server:[192.168.178.43:51686] Tx thread finished
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51686] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51686] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 0
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51690
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51690] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51690] Tx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51706
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51690] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51690] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51706] Rx thread finished
INFO:edgetpuvision.streaming.server:[192.168.178.43:51706] Tx thread finished
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51712
INFO:edgetpuvision.streaming.server:[192.168.178.43:51712] Upgraded to WebSocket
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:[192.168.178.43:51706] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51706] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 1
INFO:edgetpuvision.streaming.server:[192.168.178.43:51712] stream_control True
INFO:edgetpuvision.streaming.server:[192.168.178.43:51712] Enabling client
INFO:edgetpuvision.streaming.server:New web connection from 192.168.178.43:51726
INFO:edgetpuvision.streaming.server:Number of active clients: 2
INFO:edgetpuvision.streaming.server:Camera start recording
v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! tee name=t
t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! x264enc speed-preset=ultrafast tune=zerolatency threads=4 key-int-max=5 bitrate=1000 aud=False ! video/x-h264,profile=baseline ! h264parse ! video/x-h264,stream-format=byte-stream,alignment=nal ! appsink name=h264sink emit-signals=True max-buffers=1 drop=False sync=False
t. ! queue ! glfilterbin filter=glbox ! video/x-raw,format=RGB,width=224,height=224 ! appsink name=appsink emit-signals=True max-buffers=1 drop=True sync=FalseINFO:edgetpuvision.streaming.server:[192.168.178.43:51726] Rx thread finished

INFO:edgetpuvision.streaming.server:[192.168.178.43:51726] Tx thread finished
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO:edgetpuvision.streaming.server:[192.168.178.43:51726] Stopping...
INFO:edgetpuvision.streaming.server:[192.168.178.43:51726] Stopped.
INFO:edgetpuvision.streaming.server:Number of active clients: 1
```
</details>

**Comment by hjonnala** [comment]
Hi @Felix-Tr it should work normally without any issues. Please try to reflash one more time and try the demo. If you are getting into issues to update the borad normally please try the below [commands](https://coral.ai/software/#debian-packages). Thanks!!

```
# None of this is needed on Coral boards
# This repo is needed for almost all packages below
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
# This repo is needed for only python3-coral-cloudiot and python3-coral-enviro
echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt-get update
```

**Comment by Felix-Tr** [comment]
Thanks for the fast reply. I used the commands to successfully do 
```
sudo apt-get update
sudo apt-get dist-upgrade
```
but now get 

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(edgetpu_classify_server:12657): Gtk-WARNING **: 08:06:33.584: cannot open display: 
```

for 

```
edgetpu_classify_server \
> --model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite \
> --labels ${DEMO_FILES}/imagenet_labels.txt
```

Running _detect.py_ from the opencv example from [camera-example](https://github.com/google-coral/examples-camera/tree/master/opencv) with the uploaded sample image ![output_image](https://user-images.githubusercontent.com/51694852/235100018-1d686fe9-c012-476a-9f08-2f68e4ed5af9.png)
 also stops with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/usr/lib/python3/dist-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```

Can you already see the problem? In general I'm not a 100% relying on the connected camera as I want to use a stream from another camera but its weird the inference doesn't work out of the box with pycoral.

**Update:**
Okay, so turned out that this was becuase I was using the wrong combination of model, label. The [canned-models](https://github.com/google-coral/examples-camera#canned-models) for detection work. Still the issue trying to use the coral camera with `args.camera_idx=0` results in an Error:


```
Loading /home/mendel/examples-camera/all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with /home/mendel/examples-camera/all_models/coco_labels.txt labels.
select timeout
select timeout
OpenCV Error: Assertion failed (total() == 0 || data != NULL) in Mat, file /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/core/include/opencv2/core/mat.inl.hpp, line 431
Traceback (most recent call last):
  File "detect.py", line 97, in <module>
    main()
  File "detect.py", line 68, in main
    ret, frame = cap.read()
cv2.error: /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/core/include/opencv2/core/mat.inl.hpp:431: error: (-215) total() == 0 || data != NULL in function Mat
```

The commands from the [tutorial](https://coral.ai/docs/dev-board/camera/#connect-the-coral-camera) are as expected:

```
v4l2-ctl --list-devices
i.MX6S_CSI (platform:30a90000.csi1_bridge):
	/dev/video0

snapshot
Press space to take a snap, r to refocus, or q to quit
```
but pressing space saves no image. Thanks for your help!

**Comment by hjonnala** [comment]
[snapshot tool](https://github.com/hjonnala/snippets/blob/c89aea4b98f544fc2b76fb1599b2a246efb08d13/snapshot.py#L96) uses gstreamer to take the pictures. Something might went wrong when you were doing https://github.com/google-coral/edgetpu/issues/750#issue-1685767867. Please try reflashing the board and try the demos.

If you are still having the issues after refalsh please share serail console logs. Thanks!

**Comment by Felix-Tr** [comment]
Alright, if I need to use the coral camera instead of my alternative I reopen the issue, for now it works using a camera stream via http. Thanks
