### ISSUE TITLE
M.2 PCI edgetpu coral: ValueError: Failed to load delegate from libedgetpu.so.1

### ISSUE THREAD

**Issue by IMAMBAKS** [google-coral/edgetpu#756]
I installed the m.2 PCI-e in my computer but when I try to make use of it with the following cmd:

```
python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
```

I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 121, in <module>
    main()
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 71, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

I can't seem to find the problem. See the debugging logs here below:

```
ls /dev/apex_0
/dev/apex_0
```

```
sudo dmesg | grep apex

[    4.359580] apex 0000:01:00.0: enabling device (0000 -> 0002)
[    9.566533] apex 0000:01:00.0: Apex performance not throttled due to temperature
[   57.297267] apex 0000:01:00.0: Process 5435 is opening a node held by 4898.
[   63.316237] apex 0000:01:00.0: Process 5445 is opening a node held by 4898.
```

```
sudo modinfo gasket

filename:       /lib/modules/5.15.0-71-generic/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.4
description:    Google Gasket driver framework
srcversion:     2CA68DA0268ABC8C7117109
depends:
retpoline:      Y
name:           gasket
vermagic:       5.15.0-71-generic SMP mod_unload modversions
sig_id:         PKCS#7
signer:         win Secure Boot Module Signature key
sig_key:        6C:B6:1F:B3:B1:28:EF:18:89:EC:51:33:E4:DD:B1:E1:B8:AE:9A:EE
sig_hashalgo:   sha512
signature:      70:78:70:0B:F0:05:EE:5C:75:3F:A2:74:CD:F0:14:1D:98:3E:DC:A1:
                3D:19:E9:2F:5C:9C:DC:35:75:01:C8:7A:99:5B:32:69:97:D1:2B:D2:
                27:19:14:FE:89:77:41:74:2A:BB:09:68:18:32:E0:EB:2D:F2:FB:EC:
                8B:5E:FB:B6:3B:77:F2:48:4F:5D:16:E7:1E:C4:6D:B9:CC:58:34:99:
                1C:4E:84:D3:FA:80:89:DA:05:BA:10:8F:D0:E8:7A:C4:1B:33:15:E9:
                8E:8F:AA:B3:23:26:DA:DC:37:1D:75:38:69:1E:86:72:52:D0:B6:11:
                DE:E3:54:13:F1:E3:AB:EB:C1:D0:0A:10:A8:A2:5A:7A:91:A4:56:AC:
                AF:DE:66:24:5D:D3:D7:C0:69:A8:8A:B4:75:B3:D0:45:4A:42:00:3A:
                DB:15:6C:5D:78:53:FA:81:1B:3A:CA:10:6D:1C:9B:8F:32:3E:40:60:
                2C:A0:50:8A:4B:EE:94:2D:45:06:A9:6A:D2:43:96:39:B9:AF:DF:72:
                6C:78:52:C8:A8:FC:F0:43:E6:2F:E6:BB:25:2A:9B:0D:9F:C7:34:F5:
                A8:25:68:06:27:AF:7C:F4:95:CD:31:02:B0:40:AD:39:61:4D:60:F0:
                AE:D5:16:93:7A:A9:49:F0:ED:11:E3:C4:83:53:A5:F9
parm:           dma_bit_mask:int
```
```
sudo modinfo apex

filename:       /lib/modules/5.15.0-71-generic/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.2
description:    Google Apex driver
srcversion:     700E8BBBE9CC23C6EC17712
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       5.15.0-71-generic SMP mod_unload modversions
sig_id:         PKCS#7
signer:         win Secure Boot Module Signature key
sig_key:        6C:B6:1F:B3:B1:28:EF:18:89:EC:51:33:E4:DD:B1:E1:B8:AE:9A:EE
sig_hashalgo:   sha512
signature:      40:47:D8:BA:55:32:45:E0:2B:7B:AA:74:D5:E7:BC:98:69:3E:91:BD:
                2C:0E:F2:1D:05:17:E1:95:FC:8D:F3:0A:0D:74:E1:A4:08:89:86:A9:
                1C:0F:B8:63:42:8C:59:5F:F5:E5:D3:CA:39:D5:0F:E9:79:A8:6B:EE:
                98:29:EF:F0:D5:E6:B6:75:34:7A:AD:45:83:12:C0:DB:58:53:F4:16:
                D7:A0:24:00:D1:AE:88:78:8D:A5:73:12:09:7C:9A:63:5C:83:91:B4:
                B7:DF:5A:A6:E7:6C:E6:DC:28:51:CA:2B:52:D4:29:DB:B4:1D:7C:89:
                14:BF:CA:4F:21:78:6A:92:0A:81:67:01:3F:CC:FB:8E:D1:C9:27:76:
                24:5F:BB:B4:4E:D7:BC:65:49:E6:9A:78:A2:2F:EF:FB:C9:A4:E7:53:
                88:2D:72:86:F4:1A:FC:5B:D6:09:F5:48:98:2C:57:57:5D:72:6F:79:
                5B:EC:DD:C8:99:10:C1:5D:A0:1F:B1:91:03:87:8D:B0:A3:16:D0:EF:
                A0:FE:33:F0:37:30:3D:0E:59:13:67:18:DB:82:D1:81:78:14:6B:A0:
                B0:56:4C:F2:46:9D:6F:A7:43:E5:1A:A5:78:31:A4:1E:75:16:5A:CC:
                81:FA:49:0D:23:2D:13:09:0D:E7:E4:BD:6F:24:BF:9D
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
```
```
sudo dpkg -l | grep edgetpu
ii  libedgetpu1-std:amd64                 16.0                                    amd64        Support library for Edge TPU
```
```
sudo lspci -vvnnkk

System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a] (prog-if ff)
        Subsystem: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 18
        Region 0: Memory at b0100000 (64-bit, prefetchable) [size=16K]
        Region 2: Memory at b0000000 (64-bit, prefetchable) [size=1M]
        Capabilities: [80] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset- SlotPowerLimit 10.000W
                DevCtl: CorrErr- NonFatalErr- FatalErr- UnsupReq-
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+
                        MaxPayload 256 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr+ NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
                LnkCap: Port #1, Speed 5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
                        ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes, Disabled- CommClk-
                        ExtSynch- ClockPM+ AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 5GT/s (ok), Width x1 (ok)
                        TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Range ABCD, TimeoutDis+ NROPrPrP- LTR+
                         10BitTagComp- 10BitTagReq- OBFF Not Supported, ExtFmt+ EETLPPrefix-
                         EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
                         FRS- TPHComp- ExtTPHComp-
                         AtomicOpsCap: 32bit- 64bit- 128bitCAS-
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR+ OBFF Disabled,
                         AtomicOpsCtl: ReqEn-
                LnkCap2: Supported Link Speeds: 2.5-5GT/s, Crosslink- Retimer- 2Retimers- DRS-
                LnkCtl2: Target Link Speed: 5GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete- EqualizationPhase1-
                         EqualizationPhase2- EqualizationPhase3- LinkEqualizationRequest-
                         Retimer- 2Retimers- CrosslinkRes: unsupported
        Capabilities: [d0] MSI-X: Enable+ Count=128 Masked-
                Vector table: BAR=2 offset=00046800
                PBA: BAR=2 offset=00046068
        Capabilities: [e0] MSI: Enable- Count=1/32 Maskable- 64bit+
                Address: 0000000000000000  Data: 0000
        Capabilities: [f8] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [100 v1] Vendor Specific Information: ID=1556 Rev=1 Len=008 <?>
        Capabilities: [108 v1] Latency Tolerance Reporting
                Max snoop latency: 3145728ns
                Max no snoop latency: 3145728ns
        Capabilities: [110 v1] L1 PM Substates
                L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
                          PortCommonModeRestoreTime=10us PortTPowerOnTime=10us
                L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
                           T_CommonMode=0us LTR1.2_Threshold=81920ns
                L1SubCtl2: T_PwrOn=10us
        Capabilities: [200 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES- TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr+ BadTLP+ BadDLLP+ Rollover- Timeout+ AdvNonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+
                AERCap: First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Kernel driver in use: apex
        Kernel modules: apex
```

**Comment by hjonnala** [comment]
Hi, can you please share the output of `cat /sys/class/apex/apex_0/temp`.

And please try the demo with the below lines [here](https://github.com/google-coral/pycoral/blob/master/examples/classify_image.py#L41) and share the logs..

```
from pycoral.pybind._pywrap_coral import SetVerbosity as set_verbosity
set_verbosity(10)

```

**Comment by IMAMBAKS** [comment]
Output of `cat /sys/class/apex/apex_0/temp`:

`-89700`



With verbosity I'm getting the following:

```
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I tflite/edgetpu_context_direct.cc:106] USB always DFU: False (default)
I tflite/edgetpu_context_direct.cc:128] USB bulk-in queue capacity: default
I tflite/edgetpu_context_direct.cc:67] Performance expectation: Max (default)
I ./driver/mmio/host_queue.h:266] Starting in normal mode
I driver/kernel/kernel_registers.cc:83] Opening /dev/apex_0. read_only=0
I tflite/edgetpu_context_direct.cc:401] Failed to open device [Apex (PCIe)] at [/dev/apex_0]: Failed precondition: Device open failed : -1 (Connection timed out)
Traceback (most recent call last):
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 123, in <module>
    main()
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 73, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

**Comment by hjonnala** [comment]
can you install `sudo apt-get install libedgetpu1-max` and try the demo please.

**Comment by IMAMBAKS** [comment]
Unfortunately same output:

```
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I tflite/edgetpu_context_direct.cc:106] USB always DFU: False (default)
I tflite/edgetpu_context_direct.cc:128] USB bulk-in queue capacity: default
I tflite/edgetpu_context_direct.cc:67] Performance expectation: Max (default)
I ./driver/mmio/host_queue.h:266] Starting in normal mode
I driver/kernel/kernel_registers.cc:83] Opening /dev/apex_0. read_only=0
I tflite/edgetpu_context_direct.cc:401] Failed to open device [Apex (PCIe)] at [/dev/apex_0]: Failed precondition: Device open failed : -1 (Connection timed out)
Traceback (most recent call last):
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 123, in <module>
    main()
  File "/home/imambaks/coral/pycoral/examples/classify_image.py", line 73, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/home/imambaks/coral/env/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

**Comment by hjonnala** [comment]
> [    9.566533] apex 0000:01:00.0: Apex performance not throttled due to temperature

> Output of `cat /sys/class/apex/apex_0/temp`:
> 
> `-89700`

Looks some part of issue is same as this issue: https://github.com/google-coral/edgetpu/issues/741#issue-1656373274.
Do you have any other host machine to test the Coral Device?


> [   57.297267] apex 0000:01:00.0: Process 5435 is opening a node held by 4898.

Have you tried unplug and replug the device before trying the demo.

**Comment by IMAMBAKS** [comment]
Unfortunately I don't have another host. What I did try is putting it in another slot. This gives me slightly different output:

```
cat /sys/class/apex/apex_0/temp
42050
```

```
sudo dmesg | grep apex
[64823.203874] apex 0000:01:00.0: Process 553857 is opening a node held by 411483.
[64905.543621] apex 0000:01:00.0: Process 554746 is opening a node held by 411483.
[65375.725163] apex 0000:01:00.0: Process 559238 is opening a node held by 411483.
[65560.205248] apex 0000:01:00.0: entry 6144 is not free
[65646.264566] apex 0000:01:00.0: entry 6144 is not free
[65727.392647] apex 0000:01:00.0: entry 6144 is not free
[65995.703403] apex 0000:01:00.0: entry 6144 is not free
[66000.054499] apex 0000:01:00.0: Process 565934 is opening a node held by 411483.
[66007.223703] apex 0000:01:00.0: entry 6144 is not free
```




```
sudo python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[0]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[12]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[0]
I tflite/edgetpu_context_direct.cc:106] USB always DFU: False (default)
I tflite/edgetpu_context_direct.cc:128] USB bulk-in queue capacity: default
I tflite/edgetpu_context_direct.cc:67] Performance expectation: Max (default)
I ./driver/mmio/host_queue.h:266] Starting in normal mode
I driver/kernel/kernel_registers.cc:83] Opening /dev/apex_0. read_only=0
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000040000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7fb398e23000
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000044000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7fb39608d000
I driver/kernel/kernel_registers.cc:97] mmap_offset=0x0000000000048000, mmap_size=4096
I driver/kernel/kernel_registers.cc:108] Got map addr at 0x0x7fb395b7f000
I driver/kernel/kernel_registers.cc:211] Read: offset = 0x00000000000486f0, value: = 0x0000000000000000
I driver/kernel/kernel_registers.cc:190] Write: offset = 0x00000000000487a8, value = 0x0000000000000000
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000040000, mmap_size=4096, read_only=0
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000044000, mmap_size=4096, read_only=0
I driver/kernel/kernel_registers.cc:122] Closing /dev/apex_0. mmap_offset=0x0000000000048000, mmap_size=4096, read_only=0
I tflite/edgetpu_context_direct.cc:401] Failed to open device [Apex (PCIe)] at [/dev/apex_0]: Failed precondition: Could not partition page table. : 5 (Device or resource busy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.9/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
```

**Comment by IMAMBAKS** [comment]
Just an update. I am doing this for using it with frigate and I'm seeing the following:

```
2023-05-11 08:28:31.009036857  [2023-05-11 08:28:30] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-11 08:28:31.033635815  [2023-05-11 08:28:31] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-05-11 08:28:31.041854442  [2023-05-11 08:28:31] peewee_migrate                 INFO    : Starting migrations
2023-05-11 08:28:31.054031062  [2023-05-11 08:28:31] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-11 08:28:31.104890122  [2023-05-11 08:28:31] detector.coral1                INFO    : Starting detection process: 293
2023-05-11 08:28:31.124273911  [2023-05-11 08:28:31] frigate.app                    INFO    : Output process started: 295
2023-05-11 08:28:31.125434766  [2023-05-11 08:28:31] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-05-11 08:28:31.131175472  [2023-05-11 08:28:31] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

Does this mean that it is working?

**Comment by easy-and-simple** [comment]
You everywhere use sudo except when try to run python example?!?!??!
Place sudo before the line that starts example and be happy hahahha
